"""Batch 7: Лайфстайл + Характер + Социальное + Спорт + Карьера + Технологии — 18 cats, 304 items."""
import json, shutil
from pathlib import Path
from datetime import datetime, timezone

CATEGORIES_JSON = Path('/opt/untitled-pick-game-api/data/categories.json')

TRANSLATIONS = {
    "ideal_vacation": {
        "name_en": "Your ideal vacation",
        "blurb_en": "Alone in the mountains or all-inclusive with a book — find your mode",
        "items": {
            "mountains":      ("Alone in the mountains",   "summit · silence · clouds underfoot"),
            "beach_party":    ("Beach party",              "sand · music · tanned strangers"),
            "museums":        ("City museums",             "exhibitions · coffee breaks · 10 km on foot"),
            "camping":        ("Hike with friends",        "tent · campfire · 4 people and stars"),
            "spa_resort":     ("Spa resort",               "massage · robes · eastern rituals"),
            "all_incl":       ("All-inclusive with a book","sun lounger · book · free cocktail"),
            "surf_camp":      ("Surf camp",                "waves · the board · ocean to the horizon"),
            "wineries":       ("Wineries",                 "vineyards · tastings · southern Europe"),
            "gastro_tour":    ("Gastro tour",              "10 restaurants · Michelin · chefs"),
            "bicycle_trip":   ("Bike trip",                "200 km · villages and roads · tan lines"),
            "yoga_retreat":   ("Yoga retreat",             "7 days · no phone, no meat · asanas"),
            "urbex":          ("Urbex of abandoned places","flashlight · Soviet community halls · photo project"),
            "festival_tour":  ("Festival nomad",           "10 festivals · 3 countries · tent"),
            "noplans_city":   ("Zero plans in a city",     "new city · 5 days · no route"),
            "village_banya":  ("Village and banya",        "village · samovar · snow outside"),
            "observatory":    ("Cosmic observatory",       "desert · telescope · the Milky Way"),
        },
    },
    "productivity_mode": {
        "name_en": "Your productivity mode",
        "blurb_en": "16 ways to work: deadline, chaos, plan, night sprint, quiet focus",
        "items": {
            "pr_dead":   ("Deadline → one all-nighter",   "silence before that"),
            "pr_plan":   ("Plan and schedule",            "hour by hour"),
            "pr_morn":   ("Morning is sacred",            "max productivity before noon"),
            "pr_night":  ("Night sprint",                 "kicking in after 11 PM"),
            "pr_focus":  ("Quiet focus",                  "headphones, silence, flow"),
            "pr_small":  ("Many small tasks",             "instead of one big one"),
            "pr_proc":   ("Procrastinate, then sprint",   "productive at the end"),
            "pr_cafe":   ("Work from a café",             "better around people"),
            "pr_pomo":   ("Pomodoro (25/5)",              "focus by timer"),
            "pr_list":   ("To-do lists are my fetish",    "checkmarks = dopamine"),
            "pr_multi":  ("Multiple streams at once",     "somehow it works"),
            "pr_cond":   ("Only in ideal conditions",     "light, coffee, weather"),
            "pr_team":   ("In a team and shared energy",  "I don't work alone"),
            "pr_self":   ("Do it myself",                 "no delegation"),
            "pr_intuit": ("Intuitive, no system",         "but it works out"),
            "pr_only":   ("Only what I love",             "and I do it well"),
        },
    },
    "ideal_evening": {
        "name_en": "Your ideal evening",
        "blurb_en": "How you actually recharge",
        "items": {
            "ideal_evening-home-series":   ("Home with a series",           "blanket · food · no one"),
            "ideal_evening-walk-alone":    ("A walk alone",                 "headphones · thoughts"),
            "ideal_evening-party-friends": ("Party with friends",           "energy · conversations"),
            "ideal_evening-gym":           ("Gym · workout",                "barbell · cardio · sweat"),
            "ideal_evening-gaming":        ("Gaming with friends",          "Discord · streams"),
            "ideal_evening-date":          ("A date",                       "dinner · conversation"),
            "ideal_evening-cafe-book":     ("Café with a book",             "quiet · coffee · text"),
            "ideal_evening-night-city":    ("The night city",               "bars · a walk"),
            "ideal_evening-cinema":        ("The cinema",                   "big screen"),
            "ideal_evening-concert":       ("A concert",                    "crowd · sound"),
            "ideal_evening-cooking":       ("Cooking dinner",               "kitchen · rhythm · taste"),
            "ideal_evening-self-care":     ("Spa · self-care",              "bath · masks"),
            "ideal_evening-do-nothing":    ("Do nothing",                   "lying down · staring at the ceiling"),
            "ideal_evening-learn-new":     ("Learn something new",          "course · tutorial · pet project"),
            "ideal_evening-reading":       ("Read a book",                  "under the blanket · until morning"),
            "ideal_evening-long-call":     ("Long call with a friend",      "from afar · 3+ hours"),
        },
    },
    "life_rhythm": {
        "name_en": "Your life rhythm",
        "blurb_en": "How you function best",
        "items": {
            "life_rhythm-early-bird":         ("Early productive",             "5 AM · sport · errands"),
            "life_rhythm-nightowl":           ("Night owl",                    "all the best stuff after midnight"),
            "life_rhythm-chaotic":            ("Chaotic",                      "zero schedule · improvisation"),
            "life_rhythm-strict":             ("Strict discipline",            "schedule by the minute"),
            "life_rhythm-burnout":            ("Burnout",                      "lots of work · little sleep"),
            "life_rhythm-monday-start":       ("'Starting Monday'",            "always postponing"),
            "life_rhythm-cycles":             ("Productivity cycles",          "sprint + full rest"),
            "life_rhythm-pomodoro":           ("Pomodoro timer",               "25 minutes · 5 break"),
            "life_rhythm-spontaneous-sleep":  ("Sleep when tired",             "schedule? no"),
            "life_rhythm-double-life":        ("Double life",                  "day — work, night — pet project"),
            "life_rhythm-calm-pace":          ("Calm steady pace",             "no sprints · even"),
            "life_rhythm-boxer-mode":         ("Boxer mode",                   "early rising · training"),
            "life_rhythm-cafe-coworking":     ("Café or coworking",            "not at home · with people"),
            "life_rhythm-multitask":          ("Constant multitasking",        "5 windows · 3 screens"),
            "life_rhythm-digital-detox":      ("Detox mode",                   "no socials in the morning"),
            "life_rhythm-full-freedom":       ("Total freedom",                "what I want · when I want"),
        },
    },
    "core_values": {
        "name_en": "What's stronger in you",
        "blurb_en": "16 base values. Which ones are actually yours, not declarations",
        "items": {
            "adventure":    ("Pull toward adventure",       "the unknown matters more than comfort"),
            "stability":    ("Pull toward stability",       "habits and rhythm matter more than novelty"),
            "freedom":      ("Freedom above all",           "you'd never trade away your autonomy"),
            "depth":        ("Depth over breadth",          "one person > a hundred acquaintances"),
            "chaos":        ("Friendship with chaos",       "structure suffocates, improvisation heals"),
            "order":        ("Love of order",               "chaos steals energy, you need a system"),
            "closeness":    ("Closeness with people",       "warmth and contact are fuel"),
            "distance":     ("Personal distance",           "comfort comes from your own space"),
            "truth":        ("Truth at any cost",           "uncomfortable honesty beats sweet lies"),
            "tact":         ("Tact as an art",              "saying it well matters more than the truth"),
            "career":       ("Career first",                "what you do defines who you are"),
            "family":       ("Family first",                "the rest will sort itself out"),
            "logic":        ("Cold analysis",               "emotions are data, not the steering wheel"),
            "empathy":      ("Empathy as navigation",       "you read people's feelings without words"),
            "independence": ("Independence from opinions",  "I don't care what you think"),
            "belonging":    ("Belonging to a tribe",        "strength is being part of your people"),
        },
    },
    "red_flag": {
        "name_en": "Your top red flag",
        "blurb_en": "16 things you sometimes catch yourself doing",
        "items": {
            "rf_ghost":   ("Ghosting without warning",          "you disappear when it gets hard"),
            "rf_late":    ("'Read it, will reply later'",       "and sometimes never"),
            "rf_opozd":   ("Late everywhere, every time",       "chronic"),
            "rf_ok":      ("Saying 'I'm fine'",                 "when you're not"),
            "rf_3am":     ("Texting at 3 AM",                   "with serious questions"),
            "rf_think":   ("Overthinking what was said",        "and writing walls of text"),
            "rf_muha":    ("Making a mountain of a molehill",   "all in your head"),
            "rf_conf":    ("Can't hear yourself in conflict",   "forget what you wanted to say"),
            "rf_appr":    ("Dependent on approval",             "from others"),
            "rf_avoid":   ("Avoiding feelings talks",           "they wouldn't get it anyway"),
            "rf_proc":    ("Procrastinating everything",        "for later"),
            "rf_unfin":   ("Starting many, finishing few",      "47 tabs open"),
            "rf_no":      ("Saying 'no' too rarely",            "people-pleaser"),
            "rf_long":    ("Long messages instead of a call",   "wanting control over text"),
            "rf_obid":    ("'Don't like people' — but get hurt","when they don't write"),
            "rf_jealous": ("Jealous for no reason",             "your head invents it"),
        },
    },
    "green_flag": {
        "name_en": "Your top green flag",
        "blurb_en": "16 strengths that make you a normal human for others",
        "items": {
            "gf_listen":  ("I really listen",              "without interrupting"),
            "gf_remem":   ("I remember important details", "without reminders"),
            "gf_truth":   ("I tell the truth",             "even when it's awkward"),
            "gf_apol":    ("I apologize first",            "if I was wrong"),
            "gf_word":    ("I keep my word",               "no asterisks"),
            "gf_silent":  ("I can be silent next to you",  "silence is closeness too"),
            "gf_gossip":  ("I don't gossip about loved ones","ever"),
            "gf_sup":     ("I support without advice",     "if not asked"),
            "gf_no":      ("I respect 'no'",               "no offense taken"),
            "gf_help":    ("I help expecting nothing",     "just because I can"),
            "gf_glad":    ("I'm happy for friends' wins",  "sincerely, no envy"),
            "gf_self":    ("I laugh at myself",            "without bitterness"),
            "gf_judge":   ("I don't judge different views","difference is normal"),
            "gf_wrong":   ("I can say 'I was wrong'",      "not hard"),
            "gf_blame":   ("I don't look for someone to blame","in bad situations"),
            "gf_how":     ("I answer 'how are you' honestly","not 'all good' on autopilot"),
        },
    },
    "decision_style": {
        "name_en": "How you make decisions",
        "blurb_en": "16 modes of choosing: fast, slow, with the heart, with logic, through other people",
        "items": {
            "d_data":   ("Analyze data",                "then choose"),
            "d_int":    ("Listen to intuition",         "from the first moment"),
            "d_close":  ("Consult close ones",          "then decide myself"),
            "d_late":   ("Postpone till the last",      "the deadline decides"),
            "d_pmlist": ("Pros and cons list",          "two columns"),
            "d_quick":  ("Decide fast",                 "no looking back"),
            "d_sign":   ("Wait for a sign",             "and find one"),
            "d_gut":    ("My stomach will tell me",     "literally, body reaction"),
            "d_deleg":  ("Delegate the choice",         "to someone else"),
            "d_10y":    ("Think 10 years ahead",        "what would I regret"),
            "d_safe":   ("Pick the safer option",       "if unclear"),
            "d_risk":   ("Take the risk",               "the point is to try"),
            "d_ideal":  ("What would my ideal self do?","I ask myself"),
            "d_coin":   ("Flip a coin",                 "and read my reaction"),
            "d_start":  ("Just start",                  "and see what happens"),
            "d_sleep":  ("Sleep on it",                 "clearer in the morning"),
        },
    },
    "argument_style": {
        "name_en": "What you're like in an argument",
        "blurb_en": "Who you become in the moment of confrontation",
        "items": {
            "argument_style-until-end":         ("Argue till the end",           "stubborn logician"),
            "argument_style-listen-first":      ("Listen first, then reply",     "the negotiator"),
            "argument_style-joke-out":          ("Turn it all into a joke",      "defuse the tension"),
            "argument_style-walk-away":         ("Walk away if it's pointless",  "won't waste time"),
            "argument_style-facts-press":       ("Press with facts",             "data-driven"),
            "argument_style-emotion-press":     ("Press with emotion",           "energetic persuader"),
            "argument_style-mediator":          ("Try to make peace",            "mediator"),
            "argument_style-only-important":    ("Argue only if it matters",     "selective"),
            "argument_style-inner-debate":      ("Silent, but a thesis inside",  "internal debater"),
            "argument_style-see-weakness":      ("See the weak spot at once",    "analyst"),
            "argument_style-cool-fast":         ("Cool down quickly",            "no grudges"),
            "argument_style-hold-position":     ("Hold position even when hard", "principled"),
            "argument_style-admit-easy":        ("Easily admit being wrong",     "self-aware"),
            "argument_style-never-admit":       ("Never admit it right away",    "ego defense"),
            "argument_style-for-truth":         ("Argue for truth",              "Socratic method"),
            "argument_style-for-victory":       ("Argue for victory",            "competitive"),
        },
    },
    "friend_role": {
        "name_en": "What you're like in a friend group",
        "blurb_en": "16 social roles: organizer, observer, joker, diplomat",
        "items": {
            "fr_org":    ("The organizer",          "you gather everyone, plan things"),
            "fr_joke":   ("The joker",              "always with a joke at the right moment"),
            "fr_obs":    ("The observer",           "watching, not rushing to speak"),
            "fr_dipl":   ("The diplomat",           "peace matters more than being right"),
            "fr_advice": ("The adviser",            "people come to you with problems"),
            "fr_energy": ("The energizer",          "charging everyone with your energy"),
            "fr_skept":  ("The skeptic",            "sober view of any idea"),
            "fr_photo":  ("The photographer",       "chronicler of evenings"),
            "fr_late":   ("The latecomer",          "but everyone waits for you anyway"),
            "fr_provoc": ("The provocateur",        "tossing in topics that explode"),
            "fr_mom":    ("The group mom/dad",      "making sure everyone's okay"),
            "fr_disap":  ("The disappearing one",   "showing up like nothing happened"),
            "fr_first":  ("First to leave",         "at 10 PM, busy tomorrow"),
            "fr_last":   ("Last to leave",          "till dawn, till the end"),
            "fr_places": ("Knower of best places",  "restaurant, bar, route"),
            "fr_quiet":  ("The quiet soul",         "not loud, but it's not the same without you"),
        },
    },
    "chat_style": {
        "name_en": "What you're like in chat",
        "blurb_en": "16 styles: voice notes, dry replies, memes, walls of text, disappearing acts",
        "items": {
            "ch_voice":  ("5-minute voice notes",                    "because it's faster"),
            "ch_dry":    ("Dry replies",                             "'ok', 'got it', 'fine'"),
            "ch_meme":   ("Memes instead of words",                  "perfect communication"),
            "ch_long":   ("Walls of text with emoji",                "many thoughts at once"),
            "ch_read":   ("Read and disappear",                      "explain later"),
            "ch_24h":    ("Reply a day later",                       "'I was busy'"),
            "ch_invis":  ("Online 24/7 but 'didn't see it'",         "honestly"),
            "ch_stick":  ("Stickers for any situation",              "pack ready"),
            "ch_short":  ("Type long, send short",                   "self-censorship"),
            "ch_punct":  ("Punctuation only for serious stuff",      "the rest is softer"),
            "ch_work":   ("Only during work hours",                  "silence after"),
            "ch_biz":    ("Only on business",                        "no fluff"),
            "ch_call":   ("Call without warning",                    "old school"),
            "ch_bullet": ("Short and to the point",                  "covers everything at once"),
            "ch_disap":  ("Disappear for a week",                    "then act like nothing happened"),
            "ch_react":  ("React with reactions, no words",          "emoji = the answer"),
        },
    },
    "conflict_persona": {
        "name_en": "Your character in a conflict",
        "blurb_en": "16 roles: peacemaker, devil's advocate, silent one, strategist, explosive leader",
        "items": {
            "cf_peace": ("The peacemaker",            "smooth out any conflict"),
            "cf_dev":   ("Devil's advocate",          "find the argument for the other side"),
            "cf_quiet": ("The silent one",            "withdraw, don't speak"),
            "cf_strat": ("The strategist",            "wait for the moment, then strike accurately"),
            "cf_boom":  ("The explosive one",         "straight into it, loud, honest"),
            "cf_dipl":  ("The diplomat",              "compromise for everyone"),
            "cf_gone":  ("The leaver",                "turn around and leave"),
            "cf_rat":   ("The rationalist",           "facts only, no emotions"),
            "cf_self":  ("The taker-on",              "victim of the situation"),
            "cf_remem": ("The rememberer",            "won't say it now, but I remember"),
            "cf_dir":   ("The blunt one",             "head-on, no filter"),
            "cf_joke":  ("Through humor",             "lower the temperature"),
            "cf_long":  ("The dragger",               "conflict goes for days"),
            "cf_close": ("The closer",                "forgot it, moving on"),
            "cf_run":   ("The runner",                "avoid at any cost"),
            "cf_refl":  ("The post-reflector",        "an hour later: 'what I should have said'"),
        },
    },
    "your_sport": {
        "name_en": "The sport that suits you",
        "blurb_en": "16 sports. Not the most popular — yours specifically",
        "items": {
            "sp_swim":   ("Swimming",                          "calm, rhythm, water"),
            "sp_climb":  ("Climbing",                          "your head decides more than your body"),
            "sp_tennis": ("Tennis",                            "one on one, reaction"),
            "sp_yoga":   ("Yoga",                              "body + breath + mind"),
            "sp_box":    ("Boxing / MMA",                      "strike, reaction, endurance"),
            "sp_cycle":  ("Cycling",                           "long distances, meditation"),
            "sp_surf":   ("Surfing",                           "the ocean and the board"),
            "sp_run":    ("Running (marathon)",                "hour after hour at your pace"),
            "sp_basket": ("Basketball",                        "team, dynamics, jumps"),
            "sp_volley": ("Beach volleyball",                  "sand, sun, two on two"),
            "sp_dance":  ("Dance (hip-hop, street)",           "rhythm and expression"),
            "sp_ski":    ("Ski / snowboard",                   "snow and slope"),
            "sp_judo":   ("Martial arts (judo, BJJ)",          "technique vs strength"),
            "sp_kayak":  ("Rowing / kayak",                    "rhythm and the river"),
            "sp_hike":   ("Hiking / trekking",                 "slow and far"),
            "sp_dive":   ("Pool / diving",                     "silence underwater"),
        },
    },
    "student_persona": {
        "name_en": "What kind of student you are",
        "blurb_en": "How you actually study",
        "items": {
            "student_persona-deadliner":       ("The deadliner",            "everything in the last night"),
            "student_persona-excellent":       ("Top of the class",         "everything to the max"),
            "student_persona-improviser":      ("The improviser",           "no prep, on charisma"),
            "student_persona-strategic-cheat": ("Strategic cheater",        "network of ready answers"),
            "student_persona-project-leader":  ("Project leader",           "organizes the team"),
            "student_persona-quiet-genius":    ("Quiet genius",             "silent · knows it all"),
            "student_persona-multitasker":     ("The parallel one",         "work + study + hobby"),
            "student_persona-procrast":        ("Chronic procrastinator",   "studying = suffering"),
            "student_persona-front-row":       ("Front-row",                "first row · first to answer"),
            "student_persona-back-row":        ("Back-row",                 "last desk"),
            "student_persona-random-attend":   ("Show up when I feel like", "40% attendance"),
            "student_persona-olympiad":        ("Olympiad student",         "beyond the curriculum"),
            "student_persona-paid-student":    ("Pay-as-you-go student",    "I pay, I study what I want"),
            "student_persona-remote-only":     ("Distance-only",            "all remote"),
            "student_persona-parent-student":  ("Parent-student",           "study + family"),
            "student_persona-skeptic":         ("Skeptic",                  "why do I even need this"),
        },
    },
    "career_vibe": {
        "name_en": "Your career vibe",
        "blurb_en": "The environment where you'd flourish",
        "items": {
            "career_vibe-startup":          ("Startup",            "risk · chaos · fast growth"),
            "career_vibe-corp":             ("Corporation",        "stability · processes"),
            "career_vibe-freelance":        ("Freelance",          "freedom · instability"),
            "career_vibe-blogging":         ("Blogging · content", "your audience · brand"),
            "career_vibe-it-dev":           ("IT development",     "code · product · remote"),
            "career_vibe-design":           ("Design",             "UX · graphics · fashion"),
            "career_vibe-own-business":     ("Own business",       "you run it yourself"),
            "career_vibe-creative-ind":     ("Creative industries","art · cinema · advertising"),
            "career_vibe-science":          ("Science · academia", "research · publications"),
            "career_vibe-public-sector":    ("Public sector · NGO","impact · stability"),
            "career_vibe-marketing":        ("Marketing and sales","people · numbers · campaigns"),
            "career_vibe-finance":          ("Finance",            "banks · investments"),
            "career_vibe-teaching":         ("Teaching",           "knowledge · communication"),
            "career_vibe-medicine":         ("Medicine · helping", "people · responsibility"),
            "career_vibe-sports-coach":     ("Sport · coaching",   "body · team"),
            "career_vibe-strange-path":     ("Weird creative path","no slot for you · pick your own"),
        },
    },
    "your_real_profession": {
        "name_en": "The profession that actually suits you",
        "blurb_en": "Not status — the one where you're in your place",
        "items": {
            "your_real_profession-pm":           ("Product Manager",      "product · priorities · team"),
            "your_real_profession-dev":          ("Software Developer",   "code · logic · architecture"),
            "your_real_profession-ux":           ("UX Designer",          "interfaces · behavior"),
            "your_real_profession-graphic":      ("Graphic Designer",     "visual · brand · composition"),
            "your_real_profession-creator":      ("Content Creator",      "video · audience · brand"),
            "your_real_profession-marketing":    ("Marketing Manager",    "campaigns · brand · numbers"),
            "your_real_profession-analyst":      ("Data Analyst",         "numbers · patterns · reports"),
            "your_real_profession-founder":      ("Founder · Entrepreneur","your own project · risk"),
            "your_real_profession-teacher":      ("Teacher · Tutor",      "knowledge · students · growth"),
            "your_real_profession-engineer":     ("Engineer",             "mechanics · construction · systems"),
            "your_real_profession-doctor":       ("Doctor",               "people · medicine · responsibility"),
            "your_real_profession-therapist":    ("Therapist · Psychologist","conversation · empathy · working with people"),
            "your_real_profession-lawyer":       ("Lawyer",               "law · arguments · details"),
            "your_real_profession-journalist":   ("Journalist",           "questions · stories · text"),
            "your_real_profession-filmmaker":    ("Filmmaker · Director", "vision · team · the picture"),
            "your_real_profession-photographer": ("Photographer",         "moment · light · composition"),
            "your_real_profession-musician":     ("Musician · Composer",  "sound · rhythm · stage"),
            "your_real_profession-writer":       ("Writer",               "text · thought · reader"),
            "your_real_profession-chef":         ("Chef",                 "taste · rhythm · product"),
            "your_real_profession-architect":    ("Architect",            "space · form · function"),
            "your_real_profession-scientist":    ("Researcher · Scientist","discovery · method · publication"),
            "your_real_profession-artist":       ("Artist",               "visual art"),
            "your_real_profession-athlete":      ("Athlete · Coach",      "body · team · result"),
            "your_real_profession-banker":       ("Investment Banker",    "deals · numbers · pressure"),
            "your_real_profession-consultant":   ("Consultant",           "strategy · clients · frameworks"),
            "your_real_profession-sales":        ("Sales Rep",            "people · negotiation · cycle"),
            "your_real_profession-pr":           ("PR Specialist",        "media · reputation · messages"),
            "your_real_profession-hr":           ("HR Specialist",        "people · processes · hiring"),
            "your_real_profession-translator":   ("Translator · Linguist","languages · precision · nuance"),
            "your_real_profession-pilot":        ("Pilot",                "the sky · technology · responsibility"),
            "your_real_profession-diplomat":     ("Diplomat",             "countries · negotiation · ritual"),
            "your_real_profession-game-dev":     ("Game Developer",       "mechanics · code · world"),
        },
    },
    "ai_tool_2020s": {
        "name_en": "Your AI tool",
        "blurb_en": "What you can't live without anymore",
        "items": {
            "ai_tool_2020s-chatgpt":     ("ChatGPT",          "OpenAI · text · logic"),
            "ai_tool_2020s-claude":      ("Claude",           "Anthropic · code · nuance"),
            "ai_tool_2020s-gemini":      ("Gemini",           "Google · multimodal"),
            "ai_tool_2020s-midjourney":  ("Midjourney",       "image generation"),
            "ai_tool_2020s-sora":        ("Sora",             "OpenAI · video"),
            "ai_tool_2020s-perplexity":  ("Perplexity",       "search with sources"),
            "ai_tool_2020s-copilot":     ("Copilot",          "Microsoft · in Office"),
            "ai_tool_2020s-notion-ai":   ("Notion AI",        "built into notes"),
            "ai_tool_2020s-dalle":       ("DALL-E",           "OpenAI · images"),
            "ai_tool_2020s-stable-diff": ("Stable Diffusion", "open-source · images"),
            "ai_tool_2020s-suno":        ("Suno",             "music generation"),
            "ai_tool_2020s-elevenlabs":  ("ElevenLabs",       "voice cloning"),
            "ai_tool_2020s-runway":      ("Runway",           "video · AI editing"),
            "ai_tool_2020s-v0-bolt":     ("v0 / Bolt",        "UI generation"),
            "ai_tool_2020s-cursor":      ("Cursor",           "AI code editor"),
            "ai_tool_2020s-yandex-giga": ("YandexGPT / GigaChat","Russian models"),
        },
    },
    "what_i_ask_ai": {
        "name_en": "What you ask AI most",
        "blurb_en": "How you actually use machine intelligence",
        "items": {
            "what_i_ask_ai-write-text":    ("Write text",                "post · email · draft"),
            "what_i_ask_ai-explain":       ("Explain a topic",           "break down something complex"),
            "what_i_ask_ai-ideate":        ("Brainstorm an idea",        "ideation"),
            "what_i_ask_ai-code":          ("Write or fix code",         "function · bug · refactor"),
            "what_i_ask_ai-translate":     ("Translate",                 "RU/EN · fast"),
            "what_i_ask_ai-format":        ("Format · markup",           "table · markdown · CSS"),
            "what_i_ask_ai-joke":          ("Joke · generate a meme",    "entertainment"),
            "what_i_ask_ai-solve-task":    ("Solve a problem",           "math · logic"),
            "what_i_ask_ai-essay":         ("Write a thesis · essay",    "long text"),
            "what_i_ask_ai-interview":     ("Prep for an interview",     "questions · answers · research"),
            "what_i_ask_ai-resume":        ("Resume · motivation letter","CV · cover letter"),
            "what_i_ask_ai-research":      ("Do research",               "gather info · compare"),
            "what_i_ask_ai-image":         ("Generate an image",         "illustration · moodboard"),
            "what_i_ask_ai-design-ui":     ("Help with design",          "UI · presentation · slides"),
            "what_i_ask_ai-decide":        ("Help me decide",            "weigh pros and cons"),
            "what_i_ask_ai-therapy":       ("Just talk",                 "one-off 'therapy'"),
        },
    },
}


def main():
    raw = json.loads(CATEGORIES_JSON.read_text(encoding="utf-8"))
    cats_by_id = {c.get("id"): c for c in raw}
    cats_done, items_done, items_missing = 0, 0, 0
    for cat_id, tr in TRANSLATIONS.items():
        cat = cats_by_id.get(cat_id)
        if cat is None: print(f"  [skip] {cat_id} not found"); continue
        cat["name_en"] = tr["name_en"]; cat["blurb_en"] = tr["blurb_en"]
        items_tr = tr.get("items", {}); n = 0
        for it in cat.get("items", []):
            iid = it.get("id")
            if iid in items_tr:
                it["name_en"], it["ctx_en"] = items_tr[iid]; n += 1
            else: items_missing += 1; print(f"    [warn] {cat_id}/{iid}")
        cats_done += 1; items_done += n
        print(f"  ✓ {cat_id}: {n}/{len(cat.get('items', []))}")
    print(f"\nCats: {cats_done}, items: {items_done}, missing: {items_missing}")
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    bak = CATEGORIES_JSON.with_name(CATEGORIES_JSON.name + f".bak.batch7.{stamp}")
    shutil.copy2(CATEGORIES_JSON, bak); print(f"Backup: {bak.name}")
    tmp = CATEGORIES_JSON.with_name(CATEGORIES_JSON.name + ".tmp")
    tmp.write_text(json.dumps(raw, ensure_ascii=False, indent=2), encoding="utf-8")
    tmp.replace(CATEGORIES_JSON); print(f"Wrote: {CATEGORIES_JSON.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
