"""Batch 8 (FINAL): Авто + Бренды + Еда + Животные + Книги + Путешествия + Философия — 17 cats, 284 items."""
import json, shutil
from pathlib import Path
from datetime import datetime, timezone

CATEGORIES_JSON = Path('/opt/untitled-pick-game-api/data/categories.json')

TRANSLATIONS = {
    "supercars": {
        "name_en": "Best supercar of the decade",
        "blurb_en": "12 cars that defined the 2010s and 2020s",
        "items": {
            "sf90":    ("Ferrari SF90 Stradale",   "Italy · 1000 hp · hybrid V8"),
            "huracan": ("Lamborghini Huracán",     "Italy · naturally aspirated V10 · 640 hp"),
            "gt3rs":   ("Porsche 911 GT3 RS",      "Germany · track-focused · ~520 hp"),
            "mc720s":  ("McLaren 720S",            "UK · carbon monocoque · 720 hp"),
            "vantage": ("Aston Martin Vantage",    "UK · AMG V8 · GT character"),
            "chiron":  ("Bugatti Chiron",          "France · W16 · 1500 hp"),
            "huayra":  ("Pagani Huayra",           "Italy · hand-built · art object"),
            "amggt":   ("Mercedes-AMG GT",         "Germany · biturbo V8 · GT balance"),
            "m4":      ("BMW M4 Competition",      "Germany · S58 · accessible power"),
            "r8":      ("Audi R8 V10",             "Germany · the last natural V10"),
            "c8":      ("Chevrolet Corvette C8",   "USA · mid-engine · price shock"),
            "lfa":     ("Lexus LFA",               "Japan · Yamaha V10 · 500 units"),
        },
    },
    "tech_brand": {
        "name_en": "Which tech brand suits you",
        "blurb_en": "Apple, Samsung, Sony, Nothing and others. Not specs — the vibe",
        "items": {
            "br_apple":   ("Apple",     "ecosystem and aesthetics"),
            "br_samsung": ("Samsung",   "Android flagship with ambition"),
            "br_sony":    ("Sony",      "audio, cameras, PlayStation"),
            "br_nothing": ("Nothing",   "transparent design, the new brand"),
            "br_google":  ("Google",    "AI and Pixel"),
            "br_msoft":   ("Microsoft", "Windows, Surface, Xbox"),
            "br_xiaomi":  ("Xiaomi",    "specs for your money"),
            "br_oneplus": ("OnePlus",   "Android for geeks"),
            "br_huawei":  ("Huawei",    "comms and camera tech"),
            "br_amazon":  ("Amazon",    "Echo, Kindle, everything-via-purchase"),
            "br_tesla":   ("Tesla",     "EVs and autopilot"),
            "br_dji":     ("DJI",       "drones and gimbals"),
            "br_gopro":   ("GoPro",     "action cameras"),
            "br_bose":    ("Bose",      "quiet premium audio"),
            "br_dyson":   ("Dyson",     "premium for the home"),
            "br_meta":    ("Meta",      "VR headsets and social media"),
        },
    },
    "jewelry_houses": {
        "name_en": "Your jewelry house",
        "blurb_en": "Pick your ideal brand in the world of luxury",
        "items": {
            "cartier":       ("Cartier",            "love · the panther · Love bracelet"),
            "tiffany":       ("Tiffany & Co.",      "blue box · Breakfast at Tiffany's · heart-and-key"),
            "bvlgari":       ("Bvlgari",            "Roman grandeur · Serpenti · colored gems"),
            "chopard":       ("Chopard",            "weddings · Happy Diamonds · Cannes Palme"),
            "graff":         ("Graff",              "the largest diamonds · fancy yellows"),
            "harry_winston": ("Harry Winston",      "jeweler to the stars · Hope · the red carpet"),
            "van_cleef":     ("Van Cleef & Arpels", "French fairy tale · Alhambra · the clover"),
            "piaget":        ("Piaget",             "ultrathin watches · Possession · ultraflat"),
            "buccellati":    ("Buccellati",         "Italian baroque · gold engraving · lace"),
            "pomellato":     ("Pomellato",          "Milanese hype · colored gems · casual"),
            "mikimoto":      ("Mikimoto",           "Japanese pearls · founder of cultured · Kokichi"),
            "de_beers":      ("De Beers",           "diamond monopolist · 'forever' · the portfolio"),
            "tasaki":        ("Tasaki",             "pearls and spikes · Japanese boldness · corals"),
            "chow_tai_fook": ("Chow Tai Fook",      "Hong Kong giant · gold · Chinese weddings"),
            "damiani":       ("Damiani",            "Italian family · Diamonds International prize"),
            "chaumet":       ("Chaumet",            "Paris atelier · Napoleon's tiaras · dandyism"),
        },
    },
    "recognizable_brands": {
        "name_en": "Most recognizable brand",
        "blurb_en": "Which global brand is the most iconic to you?",
        "items": {
            "starbucks":    ("Starbucks",      "the siren · cup with your name · frappuccino"),
            "mcdonalds":    ("McDonald's",     "golden arches · Big Mac · Ronald"),
            "chanel":       ("Chanel",         "double C · the little black dress · No. 5"),
            "mercedes":     ("Mercedes-Benz",  "three-pointed star · S-class · luxury"),
            "lufthansa":    ("Lufthansa",      "the crane · aviation · Frankfurt hub"),
            "coca_cola":    ("Coca-Cola",      "the iconic bottle · Santa Claus · the holidays are coming"),
            "nike":         ("Nike",           "the swoosh · Just Do It · Air Jordan"),
            "apple":        ("Apple",          "bitten apple · iPhone · Mac"),
            "google":       ("Google",         "colored letters · search · doodles"),
            "ferrari":      ("Ferrari",        "the prancing horse · red · Formula 1"),
            "louis_vuitton":("Louis Vuitton",  "LV monogram · trunk · French luxury"),
            "disney":       ("Disney",         "Sleeping Beauty's castle · Mickey · the ears"),
            "red_bull":     ("Red Bull",       "two bulls · gives you wings · the Wing"),
            "amazon":       ("Amazon",         "arrow from A to Z · the smile · the box"),
            "bmw":          ("BMW",            "Bavarian propeller · the kidney grille · ultimate driving machine"),
            "playboy":      ("Playboy",        "bunny in a bowtie · iconic logo · Hugh Hefner"),
        },
    },
    "world_cuisine": {
        "name_en": "Best cuisine in the world",
        "blurb_en": "16 national cuisines in one knockout round",
        "items": {
            "thai":     ("Thai",         "spicy · sour · basil and lime"),
            "italian":  ("Italian",      "pasta · olive oil · 20 regions"),
            "japanese": ("Japanese",     "umami · seasonality · ritual"),
            "mexican":  ("Mexican",      "corn · peppers · 64 kinds of chili"),
            "indian":   ("Indian",       "spices · north vs south · vegetarian power"),
            "french":   ("French",       "sauces · butter · technique"),
            "chinese":  ("Chinese",      "8 regional schools · 5000 years"),
            "turkish":  ("Turkish",      "kebabs · meze · the East-West bridge"),
            "greek":    ("Greek",        "olives · feta · the Mediterranean"),
            "korean":   ("Korean",       "fermentation · banchan · kimchi"),
            "viet":     ("Vietnamese",   "pho · herbs · light balance"),
            "spanish":  ("Spanish",      "tapas · jamón · paella"),
            "lebanese": ("Lebanese",     "hummus · tabbouleh · Levantine smarts"),
            "georgian": ("Georgian",     "khachapuri · khinkali · supra"),
            "peruvian": ("Peruvian",     "ceviche · 4000 potato varieties"),
            "ethiop":   ("Ethiopian",    "injera · wats · the shared platter"),
        },
    },
    "comfort_food": {
        "name_en": "Your top comfort food",
        "blurb_en": "16 dishes you eat not for the taste but for the feeling of home",
        "items": {
            "pasta":      ("Pasta / spaghetti",         "the all-time base comfort"),
            "pizza":      ("Pizza",                     "dough, cheese, any topping"),
            "ramen":      ("Ramen",                     "hot broth, noodles"),
            "borsch":     ("Borscht",                   "beets, meat, a spoon of sour cream"),
            "pelmeni":    ("Pelmeni / manti",           "with butter or sour cream"),
            "potato":     ("Potatoes",                  "mashed, baked, fried"),
            "plov":       ("Plov",                      "rice, lamb, carrots"),
            "bliny":      ("Blini / oladyi",            "with honey, condensed milk, caviar"),
            "sushi":      ("Sushi",                     "rice and fish, simple philosophy"),
            "burger":     ("Burger",                    "bun-patty-cheese, the classic"),
            "chicken":    ("Fried chicken",             "KFC, grandma's — any kind"),
            "khachapuri": ("Khachapuri",                "dough and melted suluguni"),
            "eggs":       ("Eggs with anything",        "the universal breakfast"),
            "maccheese":  ("Mac & cheese",              "pasta with melted cheese"),
            "tomyam":     ("Tom Yum / Tom Kha",         "sour-spicy Thai soup"),
            "chocolate":  ("Chocolate",                 "and everything that has it"),
        },
    },
    "world_desserts": {
        "name_en": "Best dessert in the world",
        "blurb_en": "16 desserts that can wreck any diet",
        "items": {
            "tiramisu":   ("Tiramisu",                  "Italy · coffee, mascarpone, cocoa"),
            "cheesecake": ("Cheesecake",                "NY · curd or sour cream"),
            "cremeb":     ("Crème brûlée",              "France · caramelized crust"),
            "macaron":    ("Macarons",                  "France · almond, color, ritual"),
            "baklava":    ("Baklava / pakhlava",        "the East · honey, nuts, dough"),
            "mochi":      ("Mochi",                     "Japan · rice jelly"),
            "schwarz":    ("Black Forest cake",         "Germany · chocolate and cherry"),
            "eclair":     ("Éclair / profiteroles",     "France · choux pastry"),
            "medovik":    ("Medovik",                   "Russia · honey layers and sour cream"),
            "napoleon":   ("Napoleon",                  "Russia/France · puff layers with cream"),
            "churros":    ("Churros with chocolate",    "Spain · crispy sticks"),
            "matcha":     ("Matcha cake",               "Japan · green tea and cream"),
            "pannacotta": ("Panna cotta",               "Italy · creamy pudding"),
            "brownie":    ("Brownie",                   "USA · dense and chocolatey"),
            "dondurma":   ("Turkish ice cream",         "Turkey · stretchy, with mastic"),
            "strudel":    ("Strudel",                   "Austria · thin pastry and apples"),
        },
    },
    "weird_animals": {
        "name_en": "The weirdest animals on Earth",
        "blurb_en": "Nature was clearly experimenting. 16 candidates",
        "items": {
            "axolotl":   ("Axolotl",              "Mexico · regenerates its brain · forever a teenager"),
            "tapir":     ("Tapir",                "South America · trunk · relative of the rhino"),
            "okapi":     ("Okapi",                "Congo · giraffe's neck · zebra's legs"),
            "tarsier":   ("Tarsier",              "Philippines · eyes bigger than the brain"),
            "platypus":  ("Platypus",             "Australia · beak · venomous spur · lays eggs"),
            "echidna":   ("Echidna",              "Australia · spines · lays eggs"),
            "seangel":   ("Sea angel",            "Arctic · semi-transparent · predatory mollusk"),
            "narwhal":   ("Narwhal",              "Arctic · the unicorn of the sea · 3-meter tusk"),
            "capybara":  ("Capybara",             "South America · biggest rodent · chill with everything"),
            "alpaca":    ("Alpaca",               "Andes · spits · permanently surprised"),
            "starnose":  ("Star-nosed mole",      "North America · 22 tentacles on the nose"),
            "jelly":     ("Lion's mane jellyfish","Arctic · 2-meter bell · 35-meter tentacles"),
            "treekang":  ("Tree kangaroo",        "New Guinea · kangaroo in a tree"),
            "ayeaye":    ("Aye-aye",              "Madagascar · probe-like middle finger"),
            "octopus":   ("Giant Pacific octopus","Pacific · 9 brains · changes color"),
            "mantaray":  ("Manta ray",            "tropics · 7-meter wingspan · plankton filter"),
        },
    },
    "essential_books": {
        "name_en": "The essential books of humanity",
        "blurb_en": "Which one is essential for you",
        "items": {
            "books-master-margarita": ("The Master and Margarita",   "Bulgakov · 1967 · mystic satire"),
            "books-crime-punishment": ("Crime and Punishment",       "Dostoevsky · 1866 · psychological novel"),
            "books-war-peace":        ("War and Peace",              "Tolstoy · 1869 · epic novel"),
            "books-1984":             ("1984",                       "Orwell · 1949 · dystopia"),
            "books-harry-potter":     ("Harry Potter and the Philosopher's Stone","Rowling · 1997 · children's fantasy"),
            "books-lord-of-rings":    ("The Lord of the Rings",      "Tolkien · 1954 · epic fantasy"),
            "books-little-prince":    ("The Little Prince",          "Saint-Exupéry · 1943 · philosophical fairy tale"),
            "books-100-years":        ("One Hundred Years of Solitude","Márquez · 1967 · magical realism"),
            "books-catcher-rye":      ("The Catcher in the Rye",     "Salinger · 1951 · teenage rebellion"),
            "books-great-gatsby":     ("The Great Gatsby",           "Fitzgerald · 1925 · American classic"),
            "books-mockingbird":      ("To Kill a Mockingbird",      "Harper Lee · 1960 · racism in the US South"),
            "books-shining":          ("The Shining",                "Stephen King · 1977 · psychological horror"),
            "books-dune":             ("Dune",                       "Frank Herbert · 1965 · science fiction"),
            "books-fahrenheit-451":   ("Fahrenheit 451",             "Bradbury · 1953 · dystopia of censorship"),
            "books-lolita":           ("Lolita",                     "Nabokov · 1955 · tragic confession"),
            "books-game-thrones":     ("A Game of Thrones",          "George R. R. Martin · 1996 · fantasy epic"),
        },
    },
    "best_dystopia_novel": {
        "name_en": "Best dystopian novel",
        "blurb_en": "Which dark world gripped you the most?",
        "items": {
            "1984":             ("1984",                          "Orwell · 1949 · Big Brother · doublethink"),
            "brave-new-world":  ("Brave New World",               "Huxley · 1932 · happiness as control tool"),
            "fahrenheit-451":   ("Fahrenheit 451",                "Bradbury · 1953 · the state burns books"),
            "handmaids-tale":   ("The Handmaid's Tale",           "Atwood · 1985 · theocracy · women as resource"),
            "clockwork-orange": ("A Clockwork Orange",            "Burgess · 1962 · violence · forced therapy"),
            "hunger-games":     ("The Hunger Games",              "Collins · 2008 · children in the arena · Panem"),
            "lord-of-flies":    ("Lord of the Flies",             "Golding · 1954 · kids without adults · chaos"),
            "we":               ("We",                            "Zamyatin · 1924 · numbers instead of names · the first"),
            "road":             ("The Road",                      "McCarthy · 2006 · Pulitzer · post-apocalyptic"),
            "never-let-me-go":  ("Never Let Me Go",               "Ishiguro · 2005 · clones · quiet tragedy"),
            "iron-heel":        ("The Iron Heel",                 "London · 1908 · oligarchy · the first dystopia"),
            "player-piano":     ("Player Piano",                  "Vonnegut · 1952 · automation · superfluous people"),
            "machine-stops":    ("The Machine Stops",             "Forster · 1909 · tech dependency · isolation"),
            "parable-of-sower": ("Parable of the Sower",          "Butler · 1993 · California collapse · survival"),
            "this-perfect-day": ("This Perfect Day",              "Levin · 1970 · UniComp · total control"),
            "drowned-world":    ("The Drowned World",             "Ballard · 1962 · climate catastrophe · regression"),
        },
    },
    "ideal_city": {
        "name_en": "Which capital is really yours",
        "blurb_en": "32 capitals of the world. Where you'd settle, not just visit",
        "items": {
            "cap_tokyo":      ("Tokyo",         "Japan · vertical megacity"),
            "cap_paris":      ("Paris",         "France · the Seine and cafés"),
            "cap_london":     ("London",        "UK · fog and pubs"),
            "cap_berlin":     ("Berlin",        "Germany · clubs and industrial"),
            "cap_rome":       ("Rome",          "Italy · the Eternal City"),
            "cap_madrid":     ("Madrid",        "Spain · tapas and plazas"),
            "cap_amsterdam":  ("Amsterdam",     "Netherlands · canals and bicycles"),
            "cap_stockholm":  ("Stockholm",     "Sweden · islands and design"),
            "cap_copenhagen": ("Copenhagen",    "Denmark · hygge and minimalism"),
            "cap_lisbon":     ("Lisbon",        "Portugal · hills and ocean"),
            "cap_vienna":     ("Vienna",        "Austria · waltz and coffee houses"),
            "cap_prague":     ("Prague",        "Czechia · Gothic and beer"),
            "cap_warsaw":     ("Warsaw",        "Poland · East and West"),
            "cap_budapest":   ("Budapest",      "Hungary · the Danube and thermal baths"),
            "cap_athens":     ("Athens",        "Greece · marble and sun"),
            "cap_dublin":     ("Dublin",        "Ireland · pubs and music"),
            "cap_seoul":      ("Seoul",         "South Korea · K-pop and delivery"),
            "cap_beijing":    ("Beijing",       "China · hutongs and skyscrapers"),
            "cap_bangkok":    ("Bangkok",       "Thailand · temples and street food"),
            "cap_singapore":  ("Singapore",     "Singapore · hub and order"),
            "cap_newdelhi":   ("New Delhi",     "India · bazaars and dust"),
            "cap_mexico":     ("Mexico City",   "Mexico · mariachi and mezcal"),
            "cap_buenos":     ("Buenos Aires",  "Argentina · tango and meat"),
            "cap_nairobi":    ("Nairobi",       "Kenya · East Africa"),
            "cap_tbilisi":    ("Tbilisi",       "Georgia · wine and khinkali"),
            "cap_astana":     ("Astana",        "Kazakhstan · steppe and futurism"),
            "cap_reykjavik":  ("Reykjavík",     "Iceland · the northern lights"),
            "cap_wellington": ("Wellington",    "New Zealand · wind and fjords"),
            "cap_helsinki":   ("Helsinki",      "Finland · lakes and saunas"),
            "cap_washington": ("Washington",    "USA · marble and museums"),
            "cap_rabat":      ("Rabat",         "Morocco · the Atlantic and the medina"),
            "cap_oslo":       ("Oslo",          "Norway · fjords and Vikings"),
        },
    },
    "ny_destinations": {
        "name_en": "Where you'd ring in the New Year",
        "blurb_en": "16 places and scenarios: from mountains to megacities",
        "items": {
            "ny_nyc":      ("New York",                      "the ball drop on Times Square"),
            "ny_sydney":   ("Sydney",                        "fireworks at the Opera House"),
            "ny_tokyo":    ("Tokyo",                         "quiet and clean"),
            "ny_dubai":    ("Dubai",                         "fireworks at Burj Khalifa"),
            "ny_reyk":     ("Reykjavík",                     "northern lights and bonfires"),
            "ny_mountains":("The mountains",                 "snow, silence, fire"),
            "ny_tropic":   ("A tropical island",             "Bali or the Maldives"),
            "ny_home":     ("Home with loved ones",          "olivier salad and series"),
            "ny_prague":   ("Prague",                        "the prettiest in Europe"),
            "ny_rio":      ("Rio de Janeiro",                "carnival-style"),
            "ny_barca":    ("Barcelona",                     "champagne and the sea"),
            "ny_edinburgh":("Edinburgh (Hogmanay)",          "Scottish New Year"),
            "ny_bangkok":  ("Bangkok",                       "warmth, lights, temples"),
            "ny_ski":      ("A ski resort",                  "Courchevel, Sölden, Gudauri"),
            "ny_amst":     ("Amsterdam",                     "bridges and lights"),
            "ny_istanbul": ("Istanbul",                      "two continents at once"),
        },
    },
    "traveler_type": {
        "name_en": "What kind of traveler you are",
        "blurb_en": "16 types: explorer, sun-lounger, foodie, museum person",
        "items": {
            "tr_expl":  ("The explorer",            "small streets, no map"),
            "tr_food":  ("The foodie",              "fly anywhere for the food"),
            "tr_muse":  ("The museum person",       "galleries, history, culture"),
            "tr_lazy":  ("The beach lounger",       "deck chair, book, sea"),
            "tr_extr":  ("The extreme traveler",    "mountains, trekking, diving"),
            "tr_spon":  ("The spontaneous one",     "bought a ticket, flying tomorrow"),
            "tr_plan":  ("The planner",             "itinerary down to the hour"),
            "tr_lux":   ("The luxury traveler",     "five stars or nowhere"),
            "tr_back":  ("The backpacker",          "minimum stuff, maximum impressions"),
            "tr_city":  ("The city person",         "megacities only"),
            "tr_solo":  ("The solo one",            "better alone, your own pace"),
            "tr_photo": ("The photographer",        "20 km on foot for one shot"),
            "tr_slow":  ("The slow traveler",       "settle in, don't rush"),
            "tr_shop":  ("The shopping tourist",    "outlets, markets, boutiques"),
            "tr_local": ("Local experience",        "Airbnb, street food, neighbors"),
            "tr_dream": ("Want to but don't go",    "the dreamer"),
        },
    },
    "beach_countries": {
        "name_en": "Sea, sun, sand",
        "blurb_en": "Which beach is your kind?",
        "items": {
            "turkey":     ("Turkey",        "Antalya · all-inclusive · warm sea"),
            "egypt":      ("Egypt",         "Red Sea · corals · Sharm El Sheikh"),
            "uae":        ("UAE",           "Dubai · white sand · luxury hotels"),
            "maldives":   ("Maldives",      "atolls · overwater bungalows · Indian Ocean"),
            "thailand":   ("Thailand",      "Phuket · Samui · tropics · affordable prices"),
            "spain":      ("Spain",         "Ibiza · Barcelona · Mediterranean"),
            "greece":     ("Greece",        "Santorini · azure sea · the islands"),
            "bora-bora":  ("Bora Bora",     "French Polynesia · the lagoon · paradise"),
            "indonesia":  ("Indonesia",     "Bali · volcanoes · rice terraces · the ocean"),
            "mexico":     ("Mexico",        "Cancún · Caribbean · white sand"),
            "italy":      ("Italy",         "Amalfi · Sardinia · azure coasts"),
            "seychelles": ("Seychelles",    "granite cliffs · clear water · turtles"),
            "cuba":       ("Cuba",          "Varadero · Caribbean beach · retro feel"),
            "australia":  ("Australia",     "Great Barrier Reef · Gold Coast · surfing"),
            "portugal":   ("Portugal",      "Algarve · the Atlantic · golden cliffs"),
            "sri-lanka":  ("Sri Lanka",     "Unawatuna · tea · elephants · Indian Ocean"),
        },
    },
    "your_philosophy": {
        "name_en": "Which philosophy is closer to you",
        "blurb_en": "The mindset that runs your decisions",
        "items": {
            "your_philosophy-live-moment":         ("Live in the moment",                      "hedonism · Epicureanism"),
            "your_philosophy-duty-discipline":     ("Duty and discipline first",               "Stoicism · Protestant ethic"),
            "your_philosophy-inner-peace":         ("Inner peace above all",                   "Buddhism · Taoism"),
            "your_philosophy-adapt-chaos":         ("The world is chaos — adapt",              "antifragility"),
            "your_philosophy-create-meaning":      ("Humans create their own meaning",         "existentialism"),
            "your_philosophy-freedom":             ("Freedom matters more than safety",        "libertarianism"),
            "your_philosophy-stability":           ("Stability matters more than risk",        "conservatism"),
            "your_philosophy-useful-not-known":    ("Better useful than famous",               "altruism · service"),
            "your_philosophy-dialectics":          ("Truth is born in argument",               "dialectics · Socrates"),
            "your_philosophy-observe-not-fight":   ("Don't fight the world — observe it",     "Stoic contemplation"),
            "your_philosophy-impermanence":        ("Everything is temporary — don't cling",   "Buddhism · impermanence"),
            "your_philosophy-self-control":        ("Success is control over yourself",        "Stoicism of Marcus Aurelius"),
            "your_philosophy-simple-life":         ("Happiness is a simple, quiet life",       "minimalism · Epicureanism"),
            "your_philosophy-legacy":              ("It matters to leave a trace",             "historical legacy"),
            "your_philosophy-intuition":           ("Sometimes you just have to feel",         "intuitionism · Romanticism"),
            "your_philosophy-strong-soft":         ("A strong person knows how to be gentle",  "Eastern wisdom · Taoism"),
        },
    },
    "adult_truth": {
        "name_en": "Which truth about adult life is closer to you",
        "blurb_en": "The conviction you arrived at growing up",
        "items": {
            "adult_truth-freedom-no-money":    ("Freedom without money quickly turns to stress","practical realism"),
            "adult_truth-work-not-meaning":    ("Work doesn't have to be the meaning of life",  "work-life balance"),
            "adult_truth-money-simplifies":    ("Money doesn't solve everything but simplifies it","financial pragmatism"),
            "adult_truth-calm-over-prove":     ("Being calm matters more than proving anything","Stoicism"),
            "adult_truth-self-rescue":         ("No one will come and rescue you",              "self-reliance"),
            "adult_truth-ambition-discipline": ("Ambition without discipline is worthless",     "execution > talent"),
            "adult_truth-less-drama":          ("Growing up means dramatizing less",            "adult sobriety"),
            "adult_truth-solitude-quiet":      ("Solitude isn't always bad, sometimes it's silence","solitude vs loneliness"),
            "adult_truth-not-lose-self":       ("The main thing is not to lose yourself chasing the norm","authenticity"),
            "adult_truth-success-different":   ("Success looks different for everyone",         "pluralism"),
            "adult_truth-stability-freedom":   ("Stability can be freedom",                     "conservative growth"),
            "adult_truth-dreams-not-jobs":     ("Not every dream needs to become a profession", "hobbies as hobbies"),
            "adult_truth-network-matters":     ("Connections matter more than they seem",       "social capital"),
            "adult_truth-leave-on-time":       ("It matters to know when to leave",             "know your limit"),
            "adult_truth-good-not-perfect":    ("Life doesn't have to be perfect to be good",   "good enough"),
            "adult_truth-own-not-best":        ("The hardest thing is to choose what's yours, not what's best","subjective fit"),
        },
    },
    "biggest_future_fear": {
        "name_en": "Your biggest fear about the future",
        "blurb_en": "What you fear most",
        "items": {
            "biggest_future_fear-not-find-self":     ("Not finding yourself",          "existential"),
            "biggest_future_fear-no-money":          ("Running out of money",          "financial"),
            "biggest_future_fear-lose-freedom":      ("Losing your freedom",           "autonomy"),
            "biggest_future_fear-burn-out":          ("Burning out too early",         "burnout"),
            "biggest_future_fear-become-ordinary":   ("Becoming ordinary and accepting it","loss of self"),
            "biggest_future_fear-wrong-profession":  ("Choosing the wrong profession", "career anxiety"),
            "biggest_future_fear-years-wasted":      ("Spending years on the wrong thing","regret"),
            "biggest_future_fear-alone":             ("Ending up alone",               "loneliness"),
            "biggest_future_fear-disappoint-self":   ("Disappointing yourself",        "self-doubt"),
            "biggest_future_fear-family-expect":     ("Not meeting family expectations","family pressure"),
            "biggest_future_fear-others-life":       ("Living someone else's life",    "inauthenticity"),
            "biggest_future_fear-not-realize":       ("Not having time to realize yourself","FOMO of life"),
            "biggest_future_fear-compare-others":    ("Constantly comparing yourself", "comparison trap"),
            "biggest_future_fear-lose-interest":     ("Losing interest in everything", "anhedonia"),
            "biggest_future_fear-comfort-trap":      ("Becoming dependent on stability","comfort trap"),
            "biggest_future_fear-never-understand":  ("Never figuring out what you want","identity crisis"),
        },
    },
}


def main():
    raw = json.loads(CATEGORIES_JSON.read_text(encoding="utf-8"))
    cats_by_id = {c.get("id"): c for c in raw}
    cats_done, items_done, items_missing = 0, 0, 0
    for cat_id, tr in TRANSLATIONS.items():
        cat = cats_by_id.get(cat_id)
        if cat is None: print(f"  [skip] {cat_id} not found"); continue
        cat["name_en"] = tr["name_en"]; cat["blurb_en"] = tr["blurb_en"]
        items_tr = tr.get("items", {}); n = 0
        for it in cat.get("items", []):
            iid = it.get("id")
            if iid in items_tr:
                it["name_en"], it["ctx_en"] = items_tr[iid]; n += 1
            else: items_missing += 1; print(f"    [warn] {cat_id}/{iid}")
        cats_done += 1; items_done += n
        print(f"  ✓ {cat_id}: {n}/{len(cat.get('items', []))}")
    print(f"\nCats: {cats_done}, items: {items_done}, missing: {items_missing}")
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    bak = CATEGORIES_JSON.with_name(CATEGORIES_JSON.name + f".bak.batch8.{stamp}")
    shutil.copy2(CATEGORIES_JSON, bak); print(f"Backup: {bak.name}")
    tmp = CATEGORIES_JSON.with_name(CATEGORIES_JSON.name + ".tmp")
    tmp.write_text(json.dumps(raw, ensure_ascii=False, indent=2), encoding="utf-8")
    tmp.replace(CATEGORIES_JSON); print(f"Wrote: {CATEGORIES_JSON.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
