"""
Seed script: 28 modern categories for 15-25yo audience (2020s drop).

Run on production:
  scp seed_2020s_categories.py root@185.186.76.89:/opt/untitled-pick-game-api/
  ssh root@185.186.76.89 'cd /opt/untitled-pick-game-api && python3 seed_2020s_categories.py'

Idempotent: skips categories that already exist by id. Logs to admin_actions.
Atomic write to categories.json.
"""

import json
import os
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

CATEGORIES_PATH = Path(os.environ.get(
    "UPG_CATEGORIES_PATH", "/opt/untitled-pick-game-api/data/categories.json"))
DB_PATH = Path(os.environ.get(
    "UPG_DB_PATH", "/opt/untitled-pick-game-api/data/db.sqlite"))


# ─── 28 NEW CATEGORIES ────────────────────────────────────────────────

NEW_CATEGORIES = [
    # ─────── INTERNET (7 themes) ───────
    {
        "id": "internet_vibe",
        "name": "Твой главный интернет-вайб",
        "blurb": "Какой ты в интернете на самом деле",
        "category_subtype": "social",
        "cluster": "Интернет",
        "default_archetype": ("Свой интернет-стиль",
            "У тебя сложился узнаваемый онлайн-почерк, не как у большинства."),
        "items": [
            ("chronically-online", "Chronically online", "живёшь в сети 24/7"),
            ("quiet-luxury", "Quiet luxury", "тихий вкус, без логотипов"),
            ("npc-mode", "NPC mode", "на автопилоте, всё по сценарию"),
            ("main-character", "Main character", "в центре своей истории"),
            ("dark-academia", "Dark academia", "кофе, библиотека, рукописи"),
            ("soft-online", "Soft online", "пастель, нежность, эстетика"),
            ("clean-online", "Clean online", "минимал, спорт, ясность"),
            ("y2k-online", "Y2K online", "нулевые с metallic finish"),
            ("vibe-shift-catcher", "Vibe shift catcher", "ловишь смены настроений"),
            ("doomscroller", "Doomscroller", "листаешь до бесконечности"),
            ("cottagecore-online", "Cottagecore online", "уют, ферма, природа"),
            ("trader-online", "Crypto/markets trader", "графики, тикеры, сделки"),
            ("nostalgic-2010s", "Nostalgic 2010s", "вайн, тумблер, мем-эра"),
            ("dark-mode-only", "Dark mode only", "никакого света на экране"),
            ("creator-wannabe", "Creator wannabe", "стримы, видео, монтаж"),
            ("lurker-forever", "Lurker forever", "всё видишь, ничего не пишешь"),
        ],
    },
    {
        "id": "your_social_network",
        "name": "Какая соцсеть реально твоя",
        "blurb": "Где ты чувствуешь себя дома",
        "category_subtype": "social",
        "cluster": "Интернет",
        "default_archetype": ("Соцсеть твоего вкуса",
            "Та платформа, что попала в твой ритм и стиль общения."),
        "items": [
            ("tiktok",     "TikTok",     "короткие видео · алгоритм"),
            ("telegram",   "Telegram",   "каналы и чаты · без алгоритма"),
            ("instagram",  "Instagram",  "фото · stories · reels"),
            ("youtube",    "YouTube",    "видео любой длины"),
            ("x-twitter",  "X (Twitter)","текст · споры · новости"),
            ("reddit",     "Reddit",     "форумы по интересам"),
            ("vk",         "VK",         "РФ-соцсеть · аудио · паблики"),
            ("pinterest",  "Pinterest",  "мудборды · эстетика"),
            ("discord",    "Discord",    "голос · сервера · гейминг"),
            ("whatsapp",   "WhatsApp",   "семья · работа · группы"),
            ("threads",    "Threads",    "X-альтернатива от Meta"),
            ("twitch",     "Twitch",     "стримы в реальном времени"),
            ("snapchat",   "Snapchat",   "исчезающие сообщения"),
            ("bereal",     "BeReal",     "спонтанное фото дня"),
            ("tumblr",     "Tumblr",     "олдскул · blog culture"),
            ("linkedin",   "LinkedIn",   "карьерная соцсеть"),
        ],
    },
    {
        "id": "messaging_style",
        "name": "Твой стиль в переписке",
        "blurb": "Как тебя узнают за десять секунд чата",
        "category_subtype": "social",
        "cluster": "Интернет",
        "default_archetype": ("Твой почерк в чатах",
            "Стиль, по которому тебя видно сразу, без подписи."),
        "items": [
            ("voice-long",     "Голосовые длиннее минуты",     "пишу — это для слабаков"),
            ("video-circles",  "Кружочки вместо текста",       "лицом — оно живее"),
            ("one-word-spam",  "Одно слово = одно сообщение",  "по 20 штук подряд"),
            ("text-walls",     "Простыни текста",              "мысль или ничего"),
            ("dry-ok-norm",    "Сухие «ок», «норм»",           "без эмоций"),
            ("stickers-only",  "Стикеры вместо слов",          "пакеты на все случаи"),
            ("memes-instead",  "Мемы вместо ответа",           "картинка скажет всё"),
            ("ahaha-no-feel",  "«Ахах» без эмоций",            "автоответ"),
            ("emoji-overload", "Эмодзи и восклицания",         "максимум выразительности"),
            ("perfect-grammar","Идеальная пунктуация",         "даже в чате"),
            ("answer-in-day",  "Отвечаешь через сутки",        "не до этого было"),
            ("answer-instant", "Отвечаешь моментально",        "телефон в руке всегда"),
            ("ghost-reader",   "Читаешь, но не отвечаешь",     "просто посмотрел"),
            ("rewriter",       "Переписываешь по 5 раз",       "перфекционизм"),
            ("schya-disappear","«Ща» — и пропадаешь",          "и так всегда"),
            ("link-no-context","Шлёшь ссылки без слов",        "сами поймут"),
        ],
    },
    {
        "id": "content_format_2020s",
        "name": "Лучший формат контента сейчас",
        "blurb": "Через что ты потребляешь мир",
        "category_subtype": "media",
        "cluster": "Интернет",
        "default_archetype": ("Твой формат",
            "Та упаковка, через которую информация заходит лучше всего."),
        "items": [
            ("tiktok-vert",    "TikTok-видео",          "вертикалка · 15-60 сек"),
            ("yt-shorts",      "YouTube Shorts",        "вертикалка YouTube"),
            ("yt-longreads",   "YouTube видео-эссе",    "20+ минут глубины"),
            ("podcasts",       "Подкасты",              "разговор · в наушниках"),
            ("streams",        "Стримы",                "Twitch, Kick · в эфире"),
            ("reels",          "Instagram Reels",       "вертикалка от Meta"),
            ("tg-channels",    "Telegram-каналы",       "пост · комменты · реакции"),
            ("tg-chats",       "Telegram-чаты",         "групповая болтовня"),
            ("x-threads",      "X-треды",               "мысль на 20 твитов"),
            ("reddit-discuss", "Reddit-обсуждения",     "сабреддиты · нити"),
            ("longreads",      "Лонгриды",              "Substack · журналы"),
            ("meme-channels",  "Мем-каналы",            "паблики и каналы"),
            ("dzen-vk-blogs",  "Дзен / VK-блоги",       "русский блогинг"),
            ("discord-servers","Discord-сервера",       "комьюнити по интересам"),
            ("audio-rooms",    "Audio rooms",           "Spotify Greenroom · X Spaces"),
            ("forums-fanfic",  "Форумы и fanfic",       "ниша · текст · лор"),
        ],
    },
    {
        "id": "tiktok_persona",
        "name": "Какой ты в TikTok/Reels",
        "blurb": "Твоя роль в самой быстрой ленте мира",
        "category_subtype": "social",
        "cluster": "Интернет",
        "default_archetype": ("Скроллер с характером",
            "Свой стиль потребления коротких видео."),
        "items": [
            ("silent-scroll",  "Молча скроллишь часами",        "без реакции"),
            ("save-all",       "Сохраняешь всё подряд",         "коллекция растёт"),
            ("send-friends",   "Кидаешь друзьям",               "это надо показать"),
            ("comments-fight", "Споришь в комментах",           "правда дороже сна"),
            ("silent-likes",   "Лайкаешь молча",                "поддерживаю"),
            ("filming-self",   "Снимаешь свои видео",           "хочешь в for you"),
            ("trends-jumper",  "Прыгаешь в каждый тренд",       "вайрал для всех"),
            ("serious-only",   "Только серьёзный контент",      "никаких танцев"),
            ("anti-algorithm", "Бойкотируешь алгоритм",         "for you ≠ твоё"),
            ("friends-only",   "Подписан только на друзей",     "не на блогеров"),
            ("block-spam",     "Блокируешь подряд",             "чистка ленты"),
            ("report-toxic",   "Репортишь токсичный контент",   "санитар интернета"),
            ("duet-stitch",    "Дуэтишь и стичишь",             "ответ — видео"),
            ("niche-tags",     "Сидишь только в нише",          "узкая лента"),
            ("rewatch-3x",     "Каждый ролик — 3 раза",         "нужно понять"),
            ("month-off",      "Забываешь приложение",          "потом возвращаешься"),
        ],
    },
    {
        "id": "meme_archetype",
        "name": "Твой мемный архетип",
        "blurb": "Через какой фильтр ты видишь интернет",
        "category_subtype": "social",
        "cluster": "Интернет",
        "default_archetype": ("Твой мемный почерк",
            "Тип юмора, через который ты разговариваешь с миром."),
        "items": [
            ("sarcastic",      "Саркастичный",                  "всё через едкий юмор"),
            ("toxic-positive", "Токсично-добрый",               "улыбка с ножом"),
            ("dead-inside",    "Дед-инсайд",                    "грустно-смешной"),
            ("vibey",          "Вайбовый",                      "positive vibes only"),
            ("dushnila",       "Душнила",                       "разжёвываю смысл"),
            ("chaotic",        "Хаотик-нейтральный",            "ноль логики, всё ок"),
            ("observer",       "Наблюдатель",                   "молчу, читаю всех"),
            ("ironic",         "Ироник",                        "всё через иронию"),
            ("emo-joke",       "Эмо-шутник",                    "грусть + смех"),
            ("sigma",          "Сигма",                         "одиночка на чиле"),
            ("alt-vibes",      "Альтушка / альт-парень",        "тёмная эстетика"),
            ("normie",         "Нормис",                        "всё что популярно"),
            ("collector",      "Коллекционер мемов",            "архив на терабайт"),
            ("family-spam",    "Репостер семейных чатов",       "бумерский фольклор"),
            ("memetic",        "Меметик",                       "создаёшь свои мемы"),
            ("troller",        "Троллер",                       "ради реакции живу"),
        ],
    },
    {
        "id": "ru_classic_memes",
        "name": "Русскоязычные мемы, которые переживут всё",
        "blurb": "Те фразы, что слышишь и говоришь чаще остальных",
        "category_subtype": "ru_cis",
        "cluster": "Интернет",
        "default_archetype": ("Знаток рунета",
            "Те мемы, которые лучше всего попадают в твою повседневную речь."),
        "items": [
            ("zhiza",       "Жиза",         "это жизненно"),
            ("baza",        "База",         "правильно сказал"),
            ("krinzh",      "Кринж",        "стыдно смотреть"),
            ("sigma-meme",  "Сигма",        "одиночка-альфа"),
            ("skuf",        "Скуф",         "мужик-обыватель за 30"),
            ("altushka",    "Альтушка",     "девушка с тёмной эстетикой"),
            ("ded-inside",  "Дед инсайд",   "грустный мем-вайб"),
            ("dushnila",    "Душнила",      "зануда-педант"),
            ("chushpan",    "Чушпан",       "слабак · из «Слова пацана»"),
            ("chiki-briki", "Чики-брики",   "звуковой мем · Сталкер"),
            ("kamon-bro",   "Камон бро",    "обращение к своим"),
            ("eto-drugoe",  "Это другое",   "типичный аргумент в споре"),
            ("zumer-cringe","Зумерский кринж","насмешка над поколением Z"),
            ("boomer",      "Бумер",        "старшее поколение"),
            ("kripovyi",    "Криповый",     "жуткий, странный"),
            ("nu-takoe",    "Ну такое",     "неопределённая оценка"),
        ],
    },

    # ─────── МУЗЫКА (3 themes) ───────
    {
        "id": "music_vibe_2020s",
        "name": "Твой музыкальный вайб 2020-х",
        "blurb": "Жанр, в котором ты сейчас живёшь",
        "category_subtype": "music",
        "cluster": "Музыка",
        "default_archetype": ("Звуковой портрет",
            "Тот жанр, в который ты погружаешься по дефолту."),
        "items": [
            ("hyperpop",     "Hyperpop",        "100 gecs · хаотичный сахар"),
            ("phonk",        "Phonk",           "memphis-style · фильтрованные басы"),
            ("kpop",         "K-pop",           "продакшн · хореография"),
            ("indie-alt",    "Indie / alternative", "арктик-манкис, FKA twigs"),
            ("rap-global",   "Рэп",             "русский и мировой"),
            ("techno",       "Techno / electronic", "берлин · клуб · 4×4"),
            ("sad-pop",      "Sad pop",         "Billie · Olivia Rodrigo"),
            ("jersey-club",  "Jersey club",     "беговые ритмы · TikTok"),
            ("afrobeats",    "Afrobeats",       "Burna Boy · Wizkid"),
            ("rnb",          "R&B",             "Frank Ocean · SZA"),
            ("lofi",         "Lo-fi · chill",   "учеба · работа · уют"),
            ("hardstyle",    "Hardstyle",       "Q-dance · 150 BPM+"),
            ("trap",         "Trap",            "808 · хай-хэты"),
            ("bedroom-pop",  "Bedroom pop",     "Clairo · Cuco · уютно"),
            ("country-2020s","Country revival", "Beyoncé · Zach Bryan"),
            ("drill",        "Drill",           "UK · NY · RU drill"),
        ],
    },
    {
        "id": "ru_music_2020s",
        "name": "Русскоязычная музыка 2020-х",
        "blurb": "Кто звучит в твоих наушниках чаще всего",
        "category_subtype": "ru_cis",
        "cluster": "Музыка",
        "default_archetype": ("Свой герой русской сцены",
            "Тот, чей трек ты ставишь на репит."),
        "items": [
            ("morgen",        "Моргенштерн",          "провокация · перформанс"),
            ("bigbabytape",   "Big Baby Tape",        "трэп · автотюн"),
            ("skriptonit",    "Скриптонит",           "качовые куплеты · Гэзаб"),
            ("anna-asti",     "ANNA ASTI",            "поп-хиты после Артик & Асти"),
            ("instasamka",    "INSTASAMKA",           "поп-рэп · TikTok"),
            ("macan",         "Macan",                "«Тёлки» · хит лета"),
            ("xhos",          "ХХОС",                 "phonk-сцена"),
            ("slava-marlow",  "Slava Marlow",         "продюсер · поп-рэп"),
            ("platina",       "Платина",              "хип-хоп лидер"),
            ("pyrokinesis",   "Pyrokinesis",          "тёмный рэп · поэзия"),
            ("kishlak",       "Кишлак",               "андеграунд · агрессия"),
            ("tima-belorus",  "Тима Белорусских",     "лиричный поп-рэп"),
            ("lida",          "Lida",                 "drill-сцена"),
            ("icegergert",    "ICEGERGERT",           "phonk · вирусные треки"),
            ("hammali-navai", "HammAli & Navai",      "поп-хиты · ностальгия"),
            ("zemfira",       "Земфира",              "легенда · до сих пор актуальна"),
        ],
    },
    {
        "id": "mood_artist",
        "name": "Лучший артист для твоего настроения",
        "blurb": "Не «самый великий», а попадающий в твой вайб",
        "category_subtype": "music",
        "cluster": "Музыка",
        "recommended_tournament_size": 32,
        "default_archetype": ("Артист твоего настроения",
            "Тот, кто звучит в наушниках в нужный момент."),
        "items": [
            ("billie",     "Billie Eilish",      "шёпот · грусть · продакшн Finneas"),
            ("taylor",     "Taylor Swift",       "универсал · поп-историк"),
            ("the-weeknd", "The Weeknd",         "ночь · сожаление · синтвейв"),
            ("drake",      "Drake",              "ритм-эн-блюз/рэп · мейнстрим"),
            ("frank",      "Frank Ocean",        "медитация · альбомы как поэмы"),
            ("sza",        "SZA",                "R&B · уязвимость"),
            ("bad-bunny",  "Bad Bunny",          "латино · реггетон"),
            ("lana",       "Lana Del Rey",       "меланхолия · Калифорния"),
            ("tyler",      "Tyler, the Creator", "хаос · продакшн"),
            ("kendrick",   "Kendrick Lamar",     "мысль · повествование"),
            ("travis",     "Travis Scott",       "high · трэп-стадион"),
            ("doja",       "Doja Cat",           "игра · поп-чудачество"),
            ("olivia",     "Olivia Rodrigo",     "драма поколения Z"),
            ("beyonce",    "Beyoncé",            "мощь · икона"),
            ("adele",      "Adele",              "катарсис · вокал"),
            ("arctic",     "Arctic Monkeys",     "британский рок · романтика"),
            ("the1975",    "The 1975",           "вайб 2010-х · синтези"),
            ("ariana",     "Ariana Grande",      "поп · пастель"),
            ("bieber",     "Justin Bieber",      "мейнстрим-поп"),
            ("post-malone","Post Malone",        "поп-трэп · меланхолия"),
            ("bigbabytape","Big Baby Tape",      "RU трэп"),
            ("morgen",     "Моргенштерн",        "RU провокация"),
            ("zemfira",    "Земфира",            "RU легенда"),
            ("skriptonit", "Скриптонит",         "RU хип-хоп"),
            ("anna-asti",  "ANNA ASTI",          "RU поп"),
            ("macan",      "Macan",              "RU поп-рэп 2024"),
            ("phonk-art",  "Phonk-волна",        "Kordhell · ICEGERGERT"),
            ("bts",        "BTS",                "K-pop икона"),
            ("blackpink",  "BLACKPINK",          "K-pop мощь"),
            ("newjeans",   "NewJeans",           "K-pop new gen"),
            ("radiohead",  "Radiohead",          "альт-рок · философия"),
            ("coldplay",   "Coldplay",           "стадион · эмоция"),
        ],
    },

    # ─────── ЭСТЕТИКА (2 themes) ───────
    {
        "id": "current_fashion_style",
        "name": "Твой стиль одежды сейчас",
        "blurb": "Как ты хочешь, чтобы тебя считывали",
        "category_subtype": "fashion",
        "cluster": "Эстетика",
        "default_archetype": ("Твой текущий код",
            "Через одежду ты сообщаешь миру кто ты."),
        "items": [
            ("streetwear",   "Streetwear",      "уличный кэжуал · оверсайз"),
            ("minimal",      "Minimal",         "два цвета · чистые линии"),
            ("old-money",    "Old money",       "дорого без логотипов"),
            ("gorpcore",     "Gorpcore",        "технический аутдор"),
            ("darkwear",     "Darkwear",        "Rick Owens · техно-чёрный"),
            ("clean-girl-boy", "Clean girl/boy","спорт + чистота"),
            ("sport-casual", "Sport casual",    "кроссовки · худи"),
            ("y2k-fashion",  "Y2K",             "нулевые · low-rise"),
            ("coquette",     "Coquette",        "банты · кружева · нежность"),
            ("vintage-thrift","Vintage thrift", "секонд-хенд микс"),
            ("techwear",     "Techwear",        "функциональный сай-фай"),
            ("preppy",       "Preppy",          "рубашки · академический"),
            ("goth-alt",     "Goth / alt",      "чёрный · цепи · ботинки"),
            ("normcore",     "Normcore",        "базовое без эстетики"),
            ("athleisure",   "Athleisure",      "дорогой спорт"),
            ("cottagecore-fashion", "Cottagecore", "пастораль · цветочки"),
        ],
    },
    {
        "id": "your_aesthetic",
        "name": "Какая эстетика тебе ближе",
        "blurb": "Визуальный мир, в котором ты живёшь",
        "category_subtype": "fashion",
        "cluster": "Эстетика",
        "default_archetype": ("Твой визуальный мир",
            "Эстетика, через которую ты хочешь видеть свою жизнь."),
        "items": [
            ("y2k",            "Y2K",             "нулевые · metallic · low-rise"),
            ("clean-girl-boy", "Clean girl/boy",  "спорт · чистота · ничего лишнего"),
            ("dark-academia",  "Dark academia",   "кожа · твид · библиотеки"),
            ("cyber",          "Cyber / cyberpunk","неон · техно · будущее"),
            ("cottagecore",    "Cottagecore",     "ферма · уют · печенье"),
            ("blokecore",      "Blokecore",       "футбол · 90-е casual"),
            ("coquette",       "Coquette",        "банты · нежность · девичье"),
            ("minimal",        "Minimal",         "белое · бежевое · линии"),
            ("old-money",      "Old money",       "тихий шик · яхты · парусина"),
            ("goblincore",     "Goblincore",      "хаос · мох · странности"),
            ("soft-grunge",    "Soft grunge",     "флисы · фланель · 90-е"),
            ("tradwife",       "Tradwife",        "homestead · возврат к корням"),
            ("acubi",          "Acubi",           "балканский интернет 2024"),
            ("mob-wife",       "Mob wife",        "90-е gangster gf · леопард"),
            ("office-siren",   "Office siren",    "work · чувственно"),
            ("maximalism",     "Maximalism",      "краски · паттерны · слои"),
        ],
    },

    # ─────── ЛАЙФСТАЙЛ (2 themes) ───────
    {
        "id": "ideal_evening",
        "name": "Твой идеальный вечер",
        "blurb": "Как ты восстанавливаешься на самом деле",
        "category_subtype": "personal",
        "cluster": "Лайфстайл",
        "default_archetype": ("Твой режим отдыха",
            "Способ перезагрузить голову и вернуться в баланс."),
        "items": [
            ("home-series",  "Дома с сериалом",          "плед · еда · никого"),
            ("walk-alone",   "Прогулка в одиночестве",   "наушники · мысли"),
            ("party-friends","Тусовка с друзьями",       "энергия · разговоры"),
            ("gym",          "Спортзал · тренировка",    "штанга · кардио · пот"),
            ("gaming",       "Катка с друзьями",         "Discord · стримы"),
            ("date",         "Свидание",                 "ужин · разговоры"),
            ("cafe-book",    "Кофейня с книгой",         "тихо · кофе · текст"),
            ("night-city",   "Ночной город",             "бары · прогулка"),
            ("cinema",       "Кинотеатр",                "большой экран"),
            ("concert",      "Концерт",                  "толпа · звук"),
            ("cooking",      "Готовить ужин",            "кухня · ритм · вкус"),
            ("self-care",    "Spa · уход за собой",      "ванна · маски"),
            ("do-nothing",   "Ничего не делать",         "лежать · смотреть в потолок"),
            ("learn-new",    "Учиться чему-то новому",   "курс · туториал · pet"),
            ("reading",      "Читать книгу",             "под пледом · до утра"),
            ("long-call",    "Долгий звонок другу",      "издалека · 3+ часа"),
        ],
    },
    {
        "id": "life_rhythm",
        "name": "Твой режим жизни",
        "blurb": "Как ты функционируешь лучше всего",
        "category_subtype": "personal",
        "cluster": "Лайфстайл",
        "default_archetype": ("Твой ритм",
            "Тип расписания, в котором тебе максимально хорошо."),
        "items": [
            ("early-bird",     "Ранний продуктивный",       "5 утра · спорт · дела"),
            ("nightowl",       "Ночной",                    "всё лучшее после полуночи"),
            ("chaotic",        "Хаотичный",                 "ноль режима · импровизация"),
            ("strict",         "Жёсткая дисциплина",        "расписание по минутам"),
            ("burnout",        "Выгорание",                 "много работы · мало сна"),
            ("monday-start",   "С понедельника начну",      "вечно откладываешь"),
            ("cycles",         "Циклы продуктивности",      "спринт + полный отдых"),
            ("pomodoro",       "Pomodoro-таймер",           "25 минут · 5 пауза"),
            ("spontaneous-sleep","Сплю когда устал",        "режим? нет"),
            ("double-life",    "Двойная жизнь",             "день — работа, ночь — pet"),
            ("calm-pace",      "Спокойный размеренный",     "без рывков · ровно"),
            ("boxer-mode",     "Боксёр-режим",              "раннее вставание · тренировка"),
            ("cafe-coworking", "В кафе или коворкинге",     "не дома · с людьми"),
            ("multitask",      "Постоянная многозадачность","5 окон · 3 экрана"),
            ("digital-detox",  "Detox-режим",               "без соцсетей по утрам"),
            ("full-freedom",   "Полная свобода",            "что хочу · когда хочу"),
        ],
    },

    # ─────── КАРЬЕРА (3 themes) ───────
    {
        "id": "student_persona",
        "name": "Какой ты студент или ученик",
        "blurb": "Как ты на самом деле учишься",
        "category_subtype": "education",
        "cluster": "Карьера",
        "default_archetype": ("Твой учебный профиль",
            "Тип, в котором ты обычно проявляешься в учёбе."),
        "items": [
            ("deadliner",      "Дедлайнер",              "всё в последнюю ночь"),
            ("excellent",      "Отличник",               "всё на максимум"),
            ("improviser",     "Импровизатор",           "без подготовки на харизме"),
            ("strategic-cheat","Списывающий стратег",    "сеть готовых ответов"),
            ("project-leader", "Лидер проекта",          "организует команду"),
            ("quiet-genius",   "Тихий гений",            "молчит · знает всё"),
            ("multitasker",    "Параллельщик",           "работа + учёба + хобби"),
            ("procrast",       "Хроник-прокрастинатор",  "учёба = страдание"),
            ("front-row",      "Фронтальный",            "первый ряд · отвечает первым"),
            ("back-row",       "Бэк-сидер",              "задняя парта"),
            ("random-attend",  "Хожу когда захочу",      "посещаемость 40%"),
            ("olympiad",       "Олимпиадник",            "вне программы"),
            ("paid-student",   "Платник по жизни",       "плачу — учу что хочу"),
            ("remote-only",    "Заочник",                "всё дистанционно"),
            ("parent-student", "Родитель-студент",       "учёба + семья"),
            ("skeptic",        "Скептик",                "зачем мне это вообще"),
        ],
    },
    {
        "id": "career_vibe",
        "name": "Твой карьерный вайб",
        "blurb": "Среда, в которой ты бы расцвёл",
        "category_subtype": "career",
        "cluster": "Карьера",
        "default_archetype": ("Твой карьерный вайб",
            "Тип среды, где твои сильные стороны работают на тебя."),
        "items": [
            ("startup",       "Стартап",                "риск · хаос · быстрый рост"),
            ("corp",          "Корпорация",             "стабильность · процессы"),
            ("freelance",     "Фриланс",                "свобода · нестабильность"),
            ("blogging",      "Блогинг · контент",      "своя аудитория · бренд"),
            ("it-dev",        "IT-разработка",          "код · продукт · ремоут"),
            ("design",        "Дизайн",                 "UX · графика · мода"),
            ("own-business",  "Свой бизнес",            "оперируешь сам"),
            ("creative-ind",  "Креативные индустрии",   "арт · кино · реклама"),
            ("science",       "Наука · академия",       "ресёрч · публикации"),
            ("public-sector", "Госсектор · НКО",        "польза · стабильность"),
            ("marketing",     "Маркетинг и продажи",    "люди · цифры · кампании"),
            ("finance",       "Финансы",                "банки · инвестиции"),
            ("teaching",      "Преподавание",           "знания · коммуникация"),
            ("medicine",      "Медицина · помощь",      "люди · ответственность"),
            ("sports-coach",  "Спорт · тренерство",     "тело · команда"),
            ("strange-path",  "Странный креативный путь","нет графы — выберу свою"),
        ],
    },
    {
        "id": "your_real_profession",
        "name": "Профессия, которая реально тебе подходит",
        "blurb": "Не статусная, а та, где ты на месте",
        "category_subtype": "career",
        "cluster": "Карьера",
        "recommended_tournament_size": 32,
        "default_archetype": ("Твоё дело",
            "Профессия, в которой совпадают сильные стороны и интерес."),
        "items": [
            ("pm",          "Product Manager",     "продукт · приоритеты · команда"),
            ("dev",         "Software Developer",  "код · логика · архитектура"),
            ("ux",          "UX Designer",         "интерфейсы · поведение"),
            ("graphic",     "Graphic Designer",    "визуал · бренд · композиция"),
            ("creator",     "Content Creator",     "видео · аудитория · бренд"),
            ("marketing",   "Marketing Manager",   "кампании · бренд · цифры"),
            ("analyst",     "Data Analyst",        "цифры · паттерны · отчёты"),
            ("founder",     "Founder · Entrepreneur","свой проект · риск"),
            ("teacher",     "Teacher · Tutor",     "знания · ученики · рост"),
            ("engineer",    "Engineer",            "механика · стройка · системы"),
            ("doctor",      "Doctor",              "люди · медицина · ответственность"),
            ("therapist",   "Therapist · Психолог","разговор · эмпатия · работа с людьми"),
            ("lawyer",      "Lawyer",              "право · аргументы · детали"),
            ("journalist",  "Journalist",          "вопросы · истории · текст"),
            ("filmmaker",   "Filmmaker · Режиссёр","видение · команда · картинка"),
            ("photographer","Photographer",        "момент · свет · композиция"),
            ("musician",    "Musician · Композитор","звук · ритм · сцена"),
            ("writer",      "Writer",              "текст · мысль · читатель"),
            ("chef",        "Chef",                "вкус · ритм · продукт"),
            ("architect",   "Architect",           "пространство · форма · функция"),
            ("scientist",   "Researcher · Scientist","открытие · метод · публикация"),
            ("artist",      "Artist",              "визуальное искусство"),
            ("athlete",     "Athlete · Coach",     "тело · команда · результат"),
            ("banker",      "Investment Banker",   "сделки · цифры · напряжение"),
            ("consultant",  "Consultant",          "стратегия · клиенты · фреймворки"),
            ("sales",       "Sales Rep",           "люди · переговоры · цикл"),
            ("pr",          "PR Specialist",       "медиа · репутация · сообщения"),
            ("hr",          "HR Specialist",       "люди · процессы · найм"),
            ("translator",  "Translator · Лингвист","языки · точность · нюанс"),
            ("pilot",       "Pilot",               "небо · техника · ответственность"),
            ("diplomat",    "Diplomat",            "страны · переговоры · ритуал"),
            ("game-dev",    "Game Developer",      "механики · код · мир"),
        ],
    },

    # ─────── ТЕХНОЛОГИИ (2 themes) ───────
    {
        "id": "ai_tool_2020s",
        "name": "Твой AI-инструмент",
        "blurb": "Без чего ты теперь не можешь",
        "category_subtype": "tech",
        "cluster": "Технологии",
        "default_archetype": ("Твой AI-партнёр",
            "Инструмент, к которому ты возвращаешься чаще всего."),
        "items": [
            ("chatgpt",     "ChatGPT",            "OpenAI · текст · логика"),
            ("claude",      "Claude",             "Anthropic · код · нюанс"),
            ("gemini",      "Gemini",             "Google · мультимодальный"),
            ("midjourney",  "Midjourney",         "генерация картинок"),
            ("sora",        "Sora",               "OpenAI · видео"),
            ("perplexity",  "Perplexity",         "поиск с источниками"),
            ("copilot",     "Copilot",            "Microsoft · в Office"),
            ("notion-ai",   "Notion AI",          "встроен в заметки"),
            ("dalle",       "DALL-E",             "OpenAI · картинки"),
            ("stable-diff", "Stable Diffusion",   "open-source · картинки"),
            ("suno",        "Suno",               "генерация музыки"),
            ("elevenlabs",  "ElevenLabs",         "клонирование голоса"),
            ("runway",      "Runway",             "видео · монтаж AI"),
            ("v0-bolt",     "v0 / Bolt",          "генерация UI"),
            ("cursor",      "Cursor",             "AI-редактор кода"),
            ("yandex-giga", "YandexGPT / GigaChat","RU модели"),
        ],
    },
    {
        "id": "what_i_ask_ai",
        "name": "Что ты чаще всего просишь у AI",
        "blurb": "Через что ты используешь машинный интеллект",
        "category_subtype": "tech",
        "cluster": "Технологии",
        "default_archetype": ("Твой паттерн с AI",
            "Тип задач, через которые ты работаешь с AI."),
        "items": [
            ("write-text",   "Написать текст",       "пост · письмо · черновик"),
            ("explain",      "Объяснить тему",       "разобрать сложное"),
            ("ideate",       "Придумать идею",       "брейншторм"),
            ("code",         "Написать или исправить код","функция · баг · рефакторинг"),
            ("translate",    "Перевести",            "RU/EN · быстро"),
            ("format",       "Оформить · сверстать", "таблица · markdown · CSS"),
            ("joke",         "Пошутить · сгенерить мем","развлечение"),
            ("solve-task",   "Решить задачу",        "математика · логика"),
            ("essay",        "Написать диплом · эссе","большой текст"),
            ("interview",    "Подготовить к собесу", "вопросы · ответы · рисёрч"),
            ("resume",       "Резюме · мотивашка",   "CV · cover letter"),
            ("research",     "Сделать рисёрч",       "собрать инфу · сравнить"),
            ("image",        "Сгенерить картинку",   "иллюстрация · мудборд"),
            ("design-ui",    "Помочь с дизайном",    "UI · презентация · слайды"),
            ("decide",       "Помочь принять решение","взвесить за и против"),
            ("therapy",      "Поговорить",           "одноразовая «терапия»"),
        ],
    },

    # ─────── ИГРЫ (2 themes) ───────
    {
        "id": "addictive_game",
        "name": "Лучшая игра для залипания",
        "blurb": "Та, к которой возвращаешься снова и снова",
        "category_subtype": "gaming",
        "cluster": "Игры",
        "recommended_tournament_size": 32,
        "default_archetype": ("Игра твоей жизни",
            "Та, к которой ты возвращаешься, даже если давно не играл."),
        "items": [
            ("minecraft",   "Minecraft",        "блоки · мир · бесконечность"),
            ("roblox",      "Roblox",           "тысячи мини-игр"),
            ("fortnite",    "Fortnite",         "battle royale · скины"),
            ("valorant",    "Valorant",         "тактический шутер · агенты"),
            ("cs2",         "CS2",              "тактический шутер · киберспорт"),
            ("dota2",       "Dota 2",           "MOBA · 5v5 · глубокая"),
            ("lol",         "League of Legends","MOBA · мейнстрим"),
            ("genshin",     "Genshin Impact",   "open-world · gacha"),
            ("ml",          "Mobile Legends",   "MOBA на телефоне"),
            ("pubg",        "PUBG",             "battle royale · реалистично"),
            ("wow",         "World of Warcraft","MMORPG · легенда"),
            ("hearthstone", "Hearthstone",      "карточная · Blizzard"),
            ("clash-royale","Clash Royale",     "карточная стратегия"),
            ("brawl-stars", "Brawl Stars",      "арена · 3v3"),
            ("stardew",     "Stardew Valley",   "ферма · уют"),
            ("hollow-knight","Hollow Knight",   "metroidvania · красиво"),
            ("elden-ring",  "Elden Ring",       "open-world Souls"),
            ("witcher3",    "The Witcher 3",    "RPG · сюжет · Геральт"),
            ("gta5",        "GTA V",            "open-world · хаос"),
            ("rdr2",        "Red Dead Redemption 2","ковбои · кинематограф"),
            ("cyberpunk",   "Cyberpunk 2077",   "Найт-Сити · RPG"),
            ("baldurs",     "Baldur's Gate 3",  "RPG · D&D · сюжет"),
            ("among-us",    "Among Us",         "социальная дедукция"),
            ("apex",        "Apex Legends",     "battle royale + герои"),
            ("overwatch2",  "Overwatch 2",      "командный шутер · герои"),
            ("rocket-league","Rocket League",   "футбол на машинах"),
            ("animal-cross","Animal Crossing",  "уют · остров"),
            ("sims4",       "The Sims 4",       "симулятор жизни"),
            ("honkai-rail", "Honkai: Star Rail","gacha · сюжет"),
            ("poe",         "Path of Exile",    "ARPG · хардкор"),
            ("terraria",    "Terraria",         "2D Minecraft · крафт"),
            ("stray",       "Stray",            "кот · киберпанк · красиво"),
        ],
    },
    {
        "id": "gaming_style",
        "name": "Твой игровой стиль",
        "blurb": "Как ты ведёшь себя в виртуальном мире",
        "category_subtype": "gaming",
        "cluster": "Игры",
        "default_archetype": ("Игровой характер",
            "Тип игрока, которым ты обычно становишься."),
        "items": [
            ("solo-grinder", "Соло-гриндер",        "играю один · фарм"),
            ("teammate",     "Тиммейт",             "комфорт в команде"),
            ("toxic-carry",  "Токсик-керри",        "тащу и ругаю"),
            ("builder",      "Строитель",           "ферма · базы · мегаполисы"),
            ("explorer",     "Исследователь",       "открываю карту"),
            ("collector",    "Коллекционер",        "achievements · скины"),
            ("speedrunner",  "Speedrunner",         "на время · оптимизация"),
            ("casual",       "Casual",              "час в неделю"),
            ("pro-esports",  "Pro / esports",       "тренировки · турниры"),
            ("modder",       "Modder",              "изменяю игру"),
            ("lore-guru",    "Лор-гуру",            "читаю всё об игре"),
            ("streamer",     "Стримлю",             "Twitch · YouTube"),
            ("emotional",    "Кинестетик",          "играю на эмоциях"),
            ("tactician",    "Тактик",              "стратегия · план"),
            ("peaceful",     "Мирный",              "Civ · никого не убиваю"),
            ("rpg-philosopher","RPG-философ",       "лор > бои · диалоги"),
        ],
    },

    # ─────── ОТНОШЕНИЯ (3 themes) ───────
    {
        "id": "relationship_persona",
        "name": "Какой ты в отношениях",
        "blurb": "Как ты строишь близкие связи",
        "category_subtype": "dating",
        "cluster": "Отношения",
        "default_archetype": ("Твой стиль в любви",
            "Тип, который проявляется в близких отношениях."),
        "items": [
            ("romantic",      "Романтик",         "свидания · цветы · письма"),
            ("rational",      "Рациональный",     "договор · расписание"),
            ("anxious",       "Тревожный",        "сомнения · перепроверки"),
            ("free",          "Свободный",        "без контроля"),
            ("caring",        "Заботливый",       "всё ради партнёра"),
            ("jealous",       "Ревнивый",         "контроль через эмоцию"),
            ("calm",          "Спокойный",        "ровный фон"),
            ("playful",       "Игривый",          "приколы · мемы · лёгкость"),
            ("deep",          "Глубокий",         "только серьёзные разговоры"),
            ("controlling",   "Контролирующий",   "всё знает · всё решает"),
            ("closed",        "Замкнутый",        "трудно открыться"),
            ("open",          "Открытый",         "всё рассказывает"),
            ("demonstrative", "Демонстративный",  "PDA · общие посты"),
            ("private",       "Скрытный",         "в соцсетях ничего"),
            ("partner",       "Партнёрский",      "всё на 50/50"),
            ("supportive",    "Поддерживающий",   "рядом в трудные моменты"),
        ],
    },
    {
        "id": "green_flag_others",
        "name": "Твой главный green flag в людях",
        "blurb": "Качество, на которое ты влюбляешься быстрее всего",
        "category_subtype": "dating",
        "cluster": "Отношения",
        "default_archetype": ("Твоё «да»",
            "Качество, на которое ты ловишься быстрее остальных."),
        "items": [
            ("honesty",      "Честность",            "говорят правду в лицо"),
            ("humor",        "Юмор",                 "видят смешное в обычном"),
            ("calm-stress",  "Спокойствие в стрессе","не паникуют"),
            ("ambitions",    "Амбиции",              "знают чего хотят"),
            ("care",         "Забота о близких",     "люди важнее карьеры"),
            ("taste",        "Вкус",                 "стиль · музыка · фильмы"),
            ("intelligence", "Интеллект",            "интересно говорить"),
            ("reliability",  "Надёжность",           "держат слово"),
            ("empathy",      "Эмпатия",              "чувствуют других"),
            ("self-irony",   "Самоирония",           "смеются над собой"),
            ("curiosity",    "Любознательность",     "интересуются миром"),
            ("financial",    "Финансовая взрослость","умеют со деньгами"),
            ("boundaries",   "Уважение границ",      "понимают «нет»"),
            ("hobbies",      "Хобби и страсти",      "что-то любят"),
            ("listening",    "Умение слушать",       "не перебивают"),
            ("money-health", "Здоровое отношение к деньгам","без жадности и понтов"),
        ],
    },
    {
        "id": "red_flag_others",
        "name": "Что тебя быстрее всего отталкивает",
        "blurb": "То, что отрезает интерес мгновенно",
        "category_subtype": "dating",
        "cluster": "Отношения",
        "is_experimental": True,
        "default_archetype": ("Твоё «нет»",
            "Качество, после которого продолжать невозможно."),
        "items": [
            ("rude-waiters", "Грубость к официантам","характер виден здесь"),
            ("dushnost",     "Душность",             "разжёвывают всё"),
            ("ponty",        "Понты",                "хвастовство · бренды"),
            ("ignor",        "Игнор",                "не отвечают часами"),
            ("control",      "Контроль",             "постоянный мониторинг"),
            ("nyte",         "Нытьё",                "вечная жалоба"),
            ("chaos",        "Хаос",                 "ноль планов · всё сорвано"),
            ("no-boundary",  "Неуважение границ",    "лезут где не звали"),
            ("late",         "Постоянные опоздания", "респект через время"),
            ("ex-gossip",    "Сплетни о бывших",     "о тебе так же скажут"),
            ("no-hobbies",   "Нет хобби · пустота",  "только работа · только контент"),
            ("greedy",       "Жадность",             "считают копейки"),
            ("jealous-noreason","Ревность без повода","драма из ничего"),
            ("petty-lies",   "Ложь даже о мелочах",  "доверие сломано"),
            ("disrespect-taste","Презрение к вкусам","смеются над любимым"),
            ("no-self-irony","Нет самоиронии",       "всё всерьёз"),
        ],
    },

    # ─────── ФИЛОСОФИЯ (3 themes) ───────
    {
        "id": "your_philosophy",
        "name": "Какая философия тебе ближе",
        "blurb": "Установка, которая управляет твоими решениями",
        "category_subtype": "philosophy",
        "cluster": "Философия",
        "default_archetype": ("Твоя философия по жизни",
            "Базовая установка, которая управляет твоими решениями."),
        "items": [
            ("live-moment",     "Жить в моменте",                                       "гедонизм · эпикурейство"),
            ("duty-discipline", "Сначала долг и дисциплина",                            "стоицизм · протестантская этика"),
            ("inner-peace",     "Главное — внутренний покой",                           "буддизм · даосизм"),
            ("adapt-chaos",     "Мир хаотичен — нужно адаптироваться",                  "антихрупкость"),
            ("create-meaning",  "Человек сам создаёт смысл",                            "экзистенциализм"),
            ("freedom",         "Свобода важнее безопасности",                          "либертарианство"),
            ("stability",       "Стабильность важнее риска",                            "консерватизм"),
            ("useful-not-known","Лучше быть полезным, чем известным",                   "альтруизм · служение"),
            ("dialectics",      "Истина рождается в споре",                             "диалектика · Сократ"),
            ("observe-not-fight","Не спорить с миром, а наблюдать",                     "стоическое созерцание"),
            ("impermanence",    "Всё временно — не цепляйся",                           "буддизм · непостоянство"),
            ("self-control",    "Успех — это контроль над собой",                       "стоицизм Марка Аврелия"),
            ("simple-life",     "Счастье — простая жизнь без лишнего шума",             "минимализм · эпикурейство"),
            ("legacy",          "Важно оставить след",                                  "историческое наследие"),
            ("intuition",       "Иногда надо просто чувствовать",                       "интуитивизм · романтизм"),
            ("strong-soft",     "Сильный человек умеет быть мягким",                    "восточная мудрость · даосизм"),
        ],
    },
    {
        "id": "adult_truth",
        "name": "Какая правда про взрослую жизнь тебе ближе",
        "blurb": "Установка, к которой ты пришёл взрослея",
        "category_subtype": "philosophy",
        "cluster": "Философия",
        "is_experimental": True,
        "default_archetype": ("Твоя правда о жизни",
            "Установка, проверенная собственным опытом взросления."),
        "items": [
            ("freedom-no-money",  "Свобода без денег быстро превращается в стресс",   "практический реализм"),
            ("work-not-meaning",  "Работа не обязана быть смыслом жизни",             "work-life balance"),
            ("money-simplifies",  "Деньги не решают всё, но упрощают почти всё",      "финансовый прагматизм"),
            ("calm-over-prove",   "Быть спокойным важнее, чем что-то доказать",       "стоицизм"),
            ("self-rescue",       "Никто не придёт и не спасёт",                      "self-reliance"),
            ("ambition-discipline","Амбиции без дисциплины ничего не стоят",          "execution > talent"),
            ("less-drama",        "Взросление — это меньше драматизировать",          "взрослая трезвость"),
            ("solitude-quiet",    "Одиночество не всегда плохо, иногда это тишина",   "solitude vs loneliness"),
            ("not-lose-self",     "Главное — не потерять себя в погоне за нормой",    "автентичность"),
            ("success-different", "Успех у всех выглядит по-разному",                 "плюрализм"),
            ("stability-freedom", "Стабильность может быть свободой",                 "консервативный рост"),
            ("dreams-not-jobs",   "Не все мечты обязаны стать профессией",            "хобби как хобби"),
            ("network-matters",   "Связи решают больше, чем кажется",                 "сетевой капитал"),
            ("leave-on-time",     "Важно уметь уходить вовремя",                      "знай меру"),
            ("good-not-perfect",  "Жизнь не обязана быть идеальной, чтобы быть хорошей","достаточно хорошо"),
            ("own-not-best",      "Сложнее всего — выбрать не лучшее, а своё",        "subjective fit"),
        ],
    },
    {
        "id": "biggest_future_fear",
        "name": "Твой главный страх будущего",
        "blurb": "То, чего ты боишься больше всего",
        "category_subtype": "experimental",
        "cluster": "Философия",
        "is_experimental": True,
        "default_archetype": ("Твой главный страх",
            "Тревога, которая чаще всего шепчет на фоне."),
        "items": [
            ("not-find-self",    "Не найти себя",                          "экзистенциальный"),
            ("no-money",         "Остаться без денег",                     "финансовый"),
            ("lose-freedom",     "Потерять свободу",                       "автономия"),
            ("burn-out",         "Выгореть слишком рано",                  "burnout"),
            ("become-ordinary",  "Стать обычным и смириться",              "потерять самость"),
            ("wrong-profession", "Выбрать не ту профессию",                "career anxiety"),
            ("years-wasted",     "Потратить годы не туда",                 "regret"),
            ("alone",            "Остаться одному",                        "loneliness"),
            ("disappoint-self",  "Разочароваться в себе",                  "self-doubt"),
            ("family-expect",    "Не оправдать ожидания семьи",            "family pressure"),
            ("others-life",      "Жить чужую жизнь",                       "inauthenticity"),
            ("not-realize",      "Не успеть реализоваться",                "FOMO of life"),
            ("compare-others",   "Постоянно сравнивать себя с другими",    "comparison trap"),
            ("lose-interest",    "Потерять интерес ко всему",              "anhedonia"),
            ("comfort-trap",     "Стать зависимым от стабильности",        "comfort trap"),
            ("never-understand", "Так и не понять, чего хочешь",           "identity crisis"),
        ],
    },

    # ─────── ХАРАКТЕР (1 theme) ───────
    {
        "id": "argument_style",
        "name": "Какой ты в споре",
        "blurb": "Кем ты становишься в момент конфронтации",
        "category_subtype": "social",
        "cluster": "Характер",
        "default_archetype": ("Твоя манера спорить",
            "Поведение, в которое ты переключаешься в споре."),
        "items": [
            ("until-end",     "Доказываю до конца",                  "упорный логик"),
            ("listen-first",  "Сначала слушаю, потом отвечаю",       "переговорщик"),
            ("joke-out",      "Перевожу всё в шутку",                "снимаю напряжение"),
            ("walk-away",     "Ухожу, если спор тупой",              "не трачу время"),
            ("facts-press",   "Давлю фактами",                       "data-driven"),
            ("emotion-press", "Давлю эмоцией",                       "энергичный убеждатель"),
            ("mediator",      "Пытаюсь всех помирить",               "медиатор"),
            ("only-important","Спорю только если важно",             "выборочный"),
            ("inner-debate",  "Молчу, но внутри уже диссертация",    "внутренний дебатчик"),
            ("see-weakness",  "Сразу вижу слабое место",             "аналитик"),
            ("cool-fast",     "Быстро остываю",                      "не злопамятный"),
            ("hold-position", "Держу позицию даже тяжело",           "принципиальный"),
            ("admit-easy",    "Легко признаю что неправ",            "self-aware"),
            ("never-admit",   "Никогда не признаю это сразу",        "защита эго"),
            ("for-truth",     "Спорю ради истины",                   "сократический метод"),
            ("for-victory",   "Спорю ради победы",                   "конкурентный"),
        ],
    },
]


# ─── APPLY ────────────────────────────────────────────────────────────

def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def build_full_category(spec, now):
    """Convert compact spec → full category dict."""
    items = []
    used_ids = set()
    for tup in spec["items"]:
        sub_slug, name, ctx = tup
        item_id = f"{spec['id']}-{sub_slug}"
        # Ensure unique within category (defensive)
        n = 2
        base = item_id
        while item_id in used_ids:
            item_id = f"{base}-{n}"
            n += 1
        used_ids.add(item_id)
        items.append({"id": item_id, "name": name, "ctx": ctx})

    cat = {
        "id": spec["id"],
        "name": spec["name"],
        "blurb": spec["blurb"],
        "category_type": spec.get("category_type", "personal"),
        "category_subtype": spec.get("category_subtype", "personal"),
        "cluster": spec["cluster"],
        "recommended_tournament_size": spec.get("recommended_tournament_size", 16),
        "is_experimental": bool(spec.get("is_experimental", False)),
        "items": items,
        "archetypes": [],
        "defaultArchetype": {
            "name": spec["default_archetype"][0],
            "body": spec["default_archetype"][1],
        },
        "submitted_by": "Uncle",
        "submitted_at": now,
    }
    return cat


def main():
    if not CATEGORIES_PATH.exists():
        print(f"FATAL: {CATEGORIES_PATH} not found")
        sys.exit(1)
    data = json.loads(CATEGORIES_PATH.read_text(encoding="utf-8"))
    existing_ids = {c.get("id") for c in data}

    now = now_iso()
    inserted = []
    skipped = []
    insert_idx = len(data)
    for i, c in enumerate(data):
        if c.get("is_name_tournament"):
            insert_idx = i
            break

    for spec in NEW_CATEGORIES:
        if spec["id"] in existing_ids:
            skipped.append(spec["id"])
            continue
        cat = build_full_category(spec, now)
        data.insert(insert_idx, cat)
        insert_idx += 1
        inserted.append(spec["id"])

    if not inserted:
        print(f"Nothing new to insert. Skipped existing: {len(skipped)}")
        return

    # Atomic write
    tmp = CATEGORIES_PATH.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    tmp.replace(CATEGORIES_PATH)

    # Audit log: one entry per inserted category
    db = sqlite3.connect(DB_PATH)
    for cid in inserted:
        db.execute(
            "INSERT INTO admin_actions (admin_user_id, action, target, extras_json, at) VALUES (?, ?, ?, ?, ?)",
            (None, "category_published", cid,
             json.dumps({"category_id": cid, "via": "seed_2020s"}, ensure_ascii=False),
             now)
        )
    db.commit()
    db.close()

    print(f"Inserted: {len(inserted)} categories")
    print(f"Skipped (already exist): {len(skipped)}")
    print(f"Total categories now: {len(data)}")
    # Show new clusters
    new_clusters = set(c["cluster"] for c in data if c.get("id") in inserted)
    print(f"Clusters touched: {sorted(new_clusters)}")


if __name__ == "__main__":
    main()
